local t = 
{
	version = 2,
	components = 
	{
		
		{
			controlID = "Panel-addRechargeActivityView_tong_Layer1_activity_Game",
			UUID = "5833d07f_f8e9_4f8c_bc78_822c8b3601b7",
			anchorPoint = "False",
			anchorPointX = "0.5",
			anchorPointY = "0.5",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "542",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				PositionX = -4,
				PositionY = -6,
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "886",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
					UUID = "9393bafe_ef56_4ba8_b943_511e743737aa",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "542",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = -1,
						PositionY = -1,
						relativeToName = "Panel",
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "886",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
							UUID = "669c3a10_c9e9_4ee5_b6c2_a058b6a31821",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "547",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/add_recharge_tong/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 3,
								PositionY = -1,
							},
							width = "891",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "ScrollView_task_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "7a6b8612_29e0_409f_936c_4fdc43a61504",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "150",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "2",
									dstBlendFunc = "771",
									height = "90",
									ignoreSize = "False",
									innerHeight = "90",
									innerWidth = "500",
									name = "ScrollView_task",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 198,
										PositionY = -7,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "470",
									ZOrder = "1",
								},
								{
									controlID = "Label_timing_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "10e78a87_a0ec_42ad_b6e5_227a8cff66c2",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_timing",
									nTextAlign = "1",
									nTextHAlign = "2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "xxxxxxxxxxxx",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 439,
										PositionY = 255,
									},
									visible = "False",
									width = "136",
									ZOrder = "1",
								},
								{
									controlID = "Label_tip1_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "76520aad_6923_434a_91dc_bf5b04136ff1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF4A43AC",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_tip1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "礼包购买金额也计入累计哟",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -143,
										PositionY = -247,
									},
									visible = "False",
									width = "244",
									ZOrder = "1",
								},
								{
									controlID = "Label_tip2_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "6c6b91f8_918a_4362_bf1b_23a8b2842081",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF5A5252",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FFF0F8FF",
										StrokeSize = 2,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_tip2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "礼包购买金额也计入累计哟",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -297,
										PositionY = -289,
									},
									visible = "False",
									width = "245",
									ZOrder = "1",
								},
								{
									controlID = "Label_recharge_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "432fe5ba_c02b_4caf_9088_df08d9985ce6",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFF0F8FF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FFF0F8FF",
										StrokeSize = 0,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_recharge",
									nTextAlign = "1",
									nTextHAlign = "2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "100元",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -270,
										PositionY = -250,
									},
									width = "60",
									ZOrder = "1",
								},
								{
									controlID = "Button_recharge_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "edbf9daf_3c6f_4ba7_bd47_37c27927643a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "97",
									ignoreSize = "True",
									name = "Button_recharge",
									normal = "ui/activity/add_recharge_tong/008.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 317,
										PositionY = -224,
									},
									UItype = "Button",
									width = "261",
									ZOrder = "1",
								},
								{
									controlID = "panel_time_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "90e14493_fa51_449a_86be_c85d2bae56a1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "200",
									ignoreSize = "False",
									name = "panel_time",
									rotation = "-13",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -334,
										PositionY = 173,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "200",
									ZOrder = "2",
									components = 
									{
										
										{
											controlID = "time_time_panel_time_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "37502aa1_402c_48bc_a9f5_931c6412ef1c",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "1",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF43357D",
												StrokeSize = 2,
											},
											height = "0",
											ignoreSize = "True",
											name = "time_time",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "2020-05-20",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -78,
												PositionY = 65,
											},
											width = "150",
											ZOrder = "4",
										},
										{
											controlID = "time_time_end_panel_time_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "2d776498_b878_4be3_b294_3fe95bfea91c",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "1",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF43357D",
												StrokeSize = 2,
											},
											height = "25",
											ignoreSize = "True",
											name = "time_time_end",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "2020-05-20",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -97,
												PositionY = 38,
											},
											width = "99",
											ZOrder = "4",
										},
										{
											controlID = "Image_time_bg_panel_time_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "d9dfe1ae_6e73_44cd_8289_64ebc4bb5ed0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "2",
											ignoreSize = "True",
											name = "Image_time_bg",
											rotation = "13",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/add_recharge/time_bg.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -24,
												PositionY = 80,
											},
											visible = "False",
											width = "2",
											ZOrder = "1",
										},
										{
											controlID = "Label_time_name_panel_time_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "2d18189b_f5c6_45b3_ad64_9c4743c90ad0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF7D393F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFF9DED8",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_time_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "活动时间",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -3,
												PositionY = 74,
											},
											visible = "False",
											width = "93",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_addRechargeActivityView_1_Image_bg_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "840558e8_aade_4978_bfb1_69793935fbf3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "57",
									ignoreSize = "True",
									name = "Image_addRechargeActivityView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/add_recharge_tong/time_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -381,
										PositionY = 246,
									},
									visible = "False",
									width = "147",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Label_addRechargeActivityView_1_Panel_root_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
							UUID = "dd7aa4df_ebe3_48b5_89b7_cdaaf12b0fe6",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "25",
							ignoreSize = "True",
							name = "Label_addRechargeActivityView_1",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "当前充值金额：",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -431,
								PositionY = -252,
							},
							visible = "False",
							width = "142",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
					UUID = "a5bfedfb_1ae7_4c7b_beb8_4f78252e9c7e",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 630,
						PositionY = -635,
						LeftPositon = 1148,
						TopPosition = 301,
						relativeToName = "Panel",
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
							UUID = "a09e05a8_f132_4249_a6e8_98366092e8c5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "88",
							ignoreSize = "False",
							name = "Panel_taskItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 200,
								PositionY = 387,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "107",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_geted_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "434ef3bc_0447_414d_8270_f7206b434273",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "89",
									ignoreSize = "False",
									name = "Panel_geted",
									sizepercentx = "129",
									sizepercenty = "101",
									sizeType = "1",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_geted_Panel_geted_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "d21bf3d6_415c_4b3a_b99b_04c2d59b7a16",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "122",
											ignoreSize = "True",
											name = "Image_geted",
											scaleX = "0.8",
											scaleY = "0.8",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/add_recharge_tong/005.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 4,
												PositionY = 51,
											},
											width = "117",
											ZOrder = "1",
										},
										{
											controlID = "Label_geted_Panel_geted_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "0944f553_fdba_4301_b306_da6e3b2e9303",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF000000",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_geted",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "รับแล้ว",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 9,
											},
											width = "50",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_get_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "69caa41a_7738_4b89_b72d_c6155a2fd139",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "89",
									ignoreSize = "False",
									name = "Panel_get",
									sizepercentx = "129",
									sizepercenty = "101",
									sizeType = "1",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 74,
										PositionY = -121,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "166",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Spine_receive_Panel_get_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "18753219_3c72_4926_b343_97934c142e63",
											classname = "MESpine",
											dstBlendFunc = "771",
											name = "Spine_receive",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											spineModel = 
											{
												SpinePath = "effect/ui_task_gift/ui_task_gift",
												animationName = "animation",
												IsLoop = true,
												IsPlay = true,
												IsUseQueue = false,
												AnimationQueue = 
												{
													
												},
											},
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 39,
											},
											visible = "False",
											ZOrder = "1",
										},
										{
											controlID = "Button_get_Panel_get_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "642969fe_7270_408c_8c1f_9ddb04d109ee",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "122",
											ignoreSize = "True",
											name = "Button_get",
											normal = "ui/activity/add_recharge_tong/007.png",
											opacity = "76",
											scaleX = "0.8",
											scaleY = "0.8",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -71,
												PositionY = 172,
											},
											UItype = "Button",
											width = "117",
											ZOrder = "1",
										},
										{
											controlID = "Label_get_Panel_get_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "38243fe8_a1ae_44c2_8ae5_e7be2ad36ba2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF231B6C",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_get",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "สามารถรับได้",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -77,
												PositionY = 129,
											},
											width = "95",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_notGet_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
									UUID = "71b35824_7930_4c26_a50d_a563be5a550d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "88",
									ignoreSize = "False",
									name = "Panel_notGet",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "129",
									sizepercenty = "100",
									sizeType = "1",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 173,
										PositionY = 24,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "166",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_notGet_Panel_notGet_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "2f553824_caab_4183_b1b9_78da0708460b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "122",
											ignoreSize = "True",
											name = "Image_notGet",
											scaleX = "0.8",
											scaleY = "0.8",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/add_recharge_tong/006.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -191,
												PositionY = 27,
											},
											width = "117",
											ZOrder = "1",
										},
										{
											controlID = "Label_money_Panel_notGet_Panel_taskItem_Panel_prefab_Panel-addRechargeActivityView_tong_Layer1_activity_Game",
											UUID = "3b0ff174_b61b_4590_8d55_e483ed1aa208",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFF0F8FF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF000000",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_money",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "100",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -198,
												PositionY = -18,
											},
											width = "36",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/add_recharge_tong/bg.png",
			"ui/activity/add_recharge_tong/008.png",
			"ui/activity/add_recharge/time_bg.png",
			"ui/activity/add_recharge_tong/time_bg.png",
			"ui/activity/add_recharge_tong/005.png",
			"ui/activity/add_recharge_tong/007.png",
			"ui/activity/add_recharge_tong/006.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

