local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-tongStudyMainView_Layer1_tong_Game",
			UUID = "af8f02ca_8781_4b4f_b745_88fe5d9ccab1",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
					UUID = "abe04cef_bdde_4f4e_8824_1a72a9e5fb2f",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1386",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg2_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "a35e3d34_43a3_4c2d_bd3f_80000f250867",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/tong/common/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Label_title_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "87e6731c_5dab_4d2d_acdc_5f9ca3d17e26",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF126280",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "26",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "30",
							ignoreSize = "True",
							name = "Label_title",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "能力分配值",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -299,
								PositionY = 198,
							},
							width = "132",
							ZOrder = "1",
						},
						{
							controlID = "Label_title1_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "0aef3623_c0b4_489d_aa87_4695f17f60f8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF126280",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "26",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "30",
							ignoreSize = "True",
							name = "Label_title1",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "技能列表",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 193,
								PositionY = 197,
							},
							width = "106",
							ZOrder = "1",
						},
						{
							controlID = "Image_dress_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "54e43b86_45f8_4e00_9cb1_c50e3a82f1d3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "14",
							ignoreSize = "True",
							name = "Image_dress",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/common/dress1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -301,
								PositionY = 177,
							},
							width = "330",
							ZOrder = "1",
						},
						{
							controlID = "Image_dress1_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "206d1a11_484e_487d_923e_499432bd55f9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "15",
							ignoreSize = "True",
							name = "Image_dress1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/common/dress2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 181,
								PositionY = -140,
							},
							width = "627",
							ZOrder = "1",
						},
						{
							controlID = "Image_dress2_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "fc5cfd80_ac16_4622_9b99_3d6dd154c151",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "13",
							ignoreSize = "True",
							name = "Image_dress2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/common/dress3.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 191,
								PositionY = 176,
							},
							width = "610",
							ZOrder = "1",
						},
						{
							controlID = "Image_dress3_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "02386e35_d70c_4347_b0b4_23d488a575a1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "14",
							ignoreSize = "True",
							name = "Image_dress3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/common/dress1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -301,
								PositionY = -138,
							},
							width = "330",
							ZOrder = "1",
						},
						{
							controlID = "Button_close_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "dbd18ae4_027b_425c_8c2b_e648ef377232",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "60",
							ignoreSize = "True",
							name = "Button_close",
							normal = "ui/common/pop_ui/pop_btn_02.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 541,
								PositionY = 215,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
						},
						{
							controlID = "Image_right_bg_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "5d9c2b4b_9df3_498f_a72a_27f3b211f953",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "291",
							ignoreSize = "True",
							name = "Image_right_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/study/001.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 192,
								PositionY = 24,
							},
							width = "576",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "ScrollView_skill_Image_right_bg_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "9ec68177_5d9c_4a5d_a19e_2142e9648546",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "291",
									ignoreSize = "False",
									innerHeight = "291",
									innerWidth = "576",
									name = "ScrollView_skill",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -288,
										PositionY = -146,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "576",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_reset_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "9177bf12_078d_4f6a_b399_330a88eb16eb",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "92",
							ignoreSize = "False",
							name = "Button_reset",
							normal = "ui/tong/common/btn1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -199,
								PositionY = -206,
							},
							UItype = "Button",
							width = "180",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_tongMonsterView_1_Button_reset_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "081f7f57_e471_4219_8402_30dfefff0bbf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_tongMonsterView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "重置",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "Panel_reset_cost_Button_reset_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "7bcd8a4b_4381_4bf0_acc7_4aad8886398d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "92",
									ignoreSize = "False",
									name = "Panel_reset_cost",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "180",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_reset_icon_Panel_reset_cost_Button_reset_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "bb8d0327_630c_4f19_b0cd_9a8b81f09fbb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_reset_icon",
											scaleX = "0.3",
											scaleY = "0.3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/500066.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -43,
												PositionY = 45,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_reset_cost_Panel_reset_cost_Button_reset_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "6cc8db14_0bb3_4ce4_bd7a_6811dbb8e6ba",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_reset_cost",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1 100",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -27,
												PositionY = 46,
											},
											width = "51",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Button_confirmAttr_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "f5470462_9751_4e05_9d3a_08e1be72eda4",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "92",
							ignoreSize = "False",
							name = "Button_confirmAttr",
							normal = "ui/tong/common/btn1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -392,
								PositionY = -206,
							},
							UItype = "Button",
							width = "180",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_tongMonsterView_1_Button_confirmAttr_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "7d3ad6ac_23cc_47bb_a880_1351d7f4a4e9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_tongMonsterView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "确定",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "Panel_cost_Button_confirmAttr_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "3db8432b_24d6_4b4a_9479_33f3309ff233",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "92",
									ignoreSize = "False",
									name = "Panel_cost",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "180",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_cost_icon_Panel_cost_Button_confirmAttr_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "dac38fd0_ef22_4146_9ab8_06424901a56b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_cost_icon",
											scaleX = "0.3",
											scaleY = "0.3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/500066.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -43,
												PositionY = 45,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_cost_Panel_cost_Button_confirmAttr_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "3dbb59cd_f2f2_44a1_bfea_17499fce0115",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_cost",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1 100",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -27,
												PositionY = 46,
											},
											width = "51",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "877b2eab_96a7_4ec6_807f_39bfab82c33e",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "110",
							ignoreSize = "False",
							name = "Panel_equipSkill",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -2,
								PositionY = -261,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "350",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_skill_1_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "9496a5c7_b9b9_4b26_8f62_a1a57ad37d51",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "110",
									ignoreSize = "False",
									name = "Panel_skill_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 52,
										PositionY = 54,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_bg_Panel_skill_1_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "d8a7335c_26d2_4163_a08c_9e5bb6724f2b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "91",
											ignoreSize = "True",
											name = "Image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/study/skillslot.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "105",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Panel_skill_1_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "4e123f26_8ba1_4757_a12f_e0a4b618856b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/affix/affix_1_jiansu.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "110",
											ZOrder = "1",
										},
										{
											controlID = "Image_select_Panel_skill_1_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "ca50b314_689d_47ea_9a8a_638596eeb9ab",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "Image_select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/study/choose.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "133",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_skill_2_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "2a8253da_e183_42d3_864d_4ab9bc401254",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "110",
									ignoreSize = "False",
									name = "Panel_skill_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 193,
										PositionY = 54,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_bg_Panel_skill_2_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "bbc825cd_373c_45a4_bfba_56befb207f05",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "91",
											ignoreSize = "True",
											name = "Image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/study/skillslot.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "105",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Panel_skill_2_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "3f9c195c_0048_4d22_b19d_c19c2518ecb6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "106",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/equipment/icon/106_106/icon1_shengli_2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "106",
											ZOrder = "1",
										},
										{
											controlID = "Image_select_Panel_skill_2_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "efdbfd74_5419_4156_8997_426f4f94da7d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "Image_select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/study/choose.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "133",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_skill_3_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "48fd4f88_ee35_42f7_a309_904ddfc7f9be",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "110",
									ignoreSize = "False",
									name = "Panel_skill_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 339,
										PositionY = 54,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_bg_Panel_skill_3_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "dde6244a_b112_4303_9832_d855bb1951c0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "91",
											ignoreSize = "True",
											name = "Image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/study/skillslot.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "105",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Panel_skill_3_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "d1cb0e57_79be_4c4a_8642_6731d1b866c2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "106",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/equipment/icon/106_106/icon1_shengli_2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "106",
											ZOrder = "1",
										},
										{
											controlID = "Image_select_Panel_skill_3_Panel_equipSkill_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
											UUID = "4aa83429_dec2_40f2_9c0e_7c508a40f799",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "Image_select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/study/choose.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "133",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Button_exit_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "319b9e8b_c35e_4bab_a683_2bd44ccae9e9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "58",
							ignoreSize = "True",
							name = "Button_exit",
							normal = "ui/common/button_big_n.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 343,
								PositionY = -209,
							},
							UItype = "Button",
							visible = "False",
							width = "134",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_tongMonsterView_1_Button_exit_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "6829b8d6_b871_4c8a_9adb_7661e21d043d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_tongMonsterView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "确定",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "51",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_attr_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "7da6041e_cadc_4cee_97d9_43510b5920ce",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "60",
							ignoreSize = "False",
							name = "Panel_attr_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -62,
								PositionY = -406,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "330",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_attr_Panel_attr_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "dd4e94ac_c5f2_4ecc_8348_c3060eaa2bec",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF126280",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_attr",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "1000",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 48,
										PositionY = -3,
									},
									width = "54",
									ZOrder = "1",
								},
								{
									controlID = "Label_name_Panel_attr_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "5c8ba91a_186b_4e54_8efa_027bf5792dd6",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF097583",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "28",
									ignoreSize = "True",
									name = "Label_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "力量",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 36,
										PositionY = -6,
									},
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "Image_tongStudyMainView_1_Panel_attr_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "8e5fca6f_6257_49a6_9f60_6f9766fd4efc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "5",
									ignoreSize = "True",
									name = "Image_tongStudyMainView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/common/line1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -31,
									},
									width = "323",
									ZOrder = "1",
								},
								{
									controlID = "Button_del_Panel_attr_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "51096783_e762_4dc1_8cef_6ed95b14558a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "42",
									ignoreSize = "True",
									name = "Button_del",
									normal = "ui/tong/study/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -138,
										PositionY = -1,
									},
									UItype = "Button",
									width = "42",
									ZOrder = "1",
								},
								{
									controlID = "Button_add_Panel_attr_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "0bbcce92_6d93_4307_878d_a1e8fe595a57",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "42",
									ignoreSize = "True",
									name = "Button_add",
									normal = "ui/tong/study/005.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = -1,
									},
									UItype = "Button",
									width = "42",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_diban_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "75381838_8d30_41ef_b0be_a1730478973d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "36",
							ignoreSize = "False",
							name = "Image_diban",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/mini_pop/13.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -369,
								PositionY = -409,
							},
							width = "130",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_num_Image_diban_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "825cfed4_9f92_4c48_87a3_5b05decd29cc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "999",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -2,
									},
									width = "46",
									ZOrder = "1",
								},
								{
									controlID = "Button_down_Image_diban_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "893d32ba_f282_4005_8354_05063a955705",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "44",
									ignoreSize = "True",
									name = "Button_down",
									normal = "ui/common/mini_pop/11.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -88,
									},
									UItype = "Button",
									width = "44",
									ZOrder = "1",
								},
								{
									controlID = "Button_up_Image_diban_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "c7b02adf_4412_43f5_9797_480e812fe1f5",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "44",
									ignoreSize = "True",
									name = "Button_up",
									normal = "ui/common/mini_pop/12.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 85,
									},
									UItype = "Button",
									width = "44",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_skill_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "4082c3f9_eff1_4dfc_945a_0f03b9e5d653",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "120",
							ignoreSize = "False",
							name = "Panel_skill_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 38,
								PositionY = -575,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_skill_icon_Panel_skill_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "4a48e4ef_4cd9_4917_96e0_71b4685228f7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_skill_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/affix/affix_1_jiansu.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "110",
									ZOrder = "1",
								},
								{
									controlID = "Image_select_Panel_skill_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "484c41f2_8992_4e90_bf93_1cbbf7553ac5",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/study/choose.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "133",
									ZOrder = "1",
								},
								{
									controlID = "Label_use_flag_Panel_skill_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "08fa230d_1028_46bc_bc24_b22fd3cd513b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF2B4A96",
										StrokeSize = 2,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_use_flag",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "使用中",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -42,
									},
									width = "65",
									ZOrder = "1",
								},
								{
									controlID = "Image_lock_Panel_skill_item_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
									UUID = "6d78a946_2f36_4529_90c0_70b7b29a216b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "88",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/study/lock.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "97",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "ScrollView_attr_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "cfc0dc16_9704_4061_9b7b_f0c1b61f8339",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "300",
							ignoreSize = "False",
							innerHeight = "300",
							innerWidth = "330",
							name = "ScrollView_attr",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -466,
								PositionY = -130,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "330",
							ZOrder = "1",
						},
						{
							controlID = "Label_title2_Panel_root_Panel-tongStudyMainView_Layer1_tong_Game",
							UUID = "225645d1_024c_4664_8b18_e0bb856ef86e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF126280",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "26",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "30",
							ignoreSize = "True",
							name = "Label_title2",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "技能槽",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 180,
								PositionY = -139,
							},
							width = "80",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/tong/common/bg.png",
			"ui/tong/common/dress1.png",
			"ui/tong/common/dress2.png",
			"ui/tong/common/dress3.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/tong/study/001.png",
			"ui/tong/common/btn1.png",
			"icon/item/goods/500066.png",
			"ui/tong/study/skillslot.png",
			"icon/affix/affix_1_jiansu.png",
			"ui/tong/study/choose.png",
			"icon/equipment/icon/106_106/icon1_shengli_2.png",
			"ui/common/button_big_n.png",
			"ui/tong/common/line1.png",
			"ui/tong/study/006.png",
			"ui/tong/study/005.png",
			"ui/common/mini_pop/13.png",
			"ui/common/mini_pop/11.png",
			"ui/common/mini_pop/12.png",
			"ui/tong/study/lock.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

