local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-tongMap_Layer1_tong_Game",
			UUID = "ca3f41a7_686b_4018_bb5f_b9e9c2c0d00f",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "1280",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "2772",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "bg_Panel-tongMap_Layer1_tong_Game",
					UUID = "8bd64a86_fa9e_4a9a_9841_e499a8617eb2",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "1280",
					ignoreSize = "False",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "fightmap/event_VITmax/bg.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						
					},
					width = "2772",
				},
				{
					controlID = "map_Panel-tongMap_Layer1_tong_Game",
					UUID = "78fc33cf_8388_4acb_9bde_55ea1263d90c",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "map",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_tongMapCloud_1_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "629b2c9e_ed61_478a_b201_2c3e5c405b23",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMapCloud_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloudBg_01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 256,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMapCloud_2_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "b0f32c2d_73b7_4699_8a05_ee656a0e2688",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMapCloud_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloudBg_02.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1024,
								PositionY = 256,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMapCloud_3_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "299bb06b_b4f6_40a5_b708_ef72844d4cfb",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMapCloud_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloudBg_03.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2048,
								PositionY = 256,
							},
							width = "724",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMap_1_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "e0ba604e_4a96_47d0_9c14_69fb34a526db",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMap_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/map_01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 256,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMap_2_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "75187daf_749e_4b44_82de_689aaceebaad",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMap_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/map_02.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1024,
								PositionY = 256,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMap_3_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "53561c72_44b5_46d3_9d38_da9b36f57f16",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMap_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/map_03.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2048,
								PositionY = 256,
							},
							width = "724",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMap_4_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "ca5a865d_b5e8_4055_af61_dd5d997d0f30",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "256",
							ignoreSize = "True",
							name = "Image_tongMap_4",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/map_04.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMap_5_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "21f4077f_b23b_4585_8749_8ed5fde26753",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "256",
							ignoreSize = "True",
							name = "Image_tongMap_5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/map_05.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1024,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMap_6_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "c62fc5d8_6d43_4517_ac9d_5ebe76962faf",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "256",
							ignoreSize = "True",
							name = "Image_tongMap_6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/map_06.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2048,
							},
							width = "724",
							ZOrder = "1",
						},
						{
							controlID = "Spine_tongMap_1_map_Panel-tongMap_Layer1_tong_Game",
							UUID = "34fbfd5e_f3b7_4e30_b832_cd93a07d5047",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_tongMap_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/eff_vitmax/eff_map/sceneEff_map/VITmax_effect_map",
								animationName = "animation",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1386,
								PositionY = 648,
							},
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_map_1_Panel-tongMap_Layer1_tong_Game",
					UUID = "57894d87_05ca_48a7_8f08_fb37bf6e4680",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "1286",
					ignoreSize = "False",
					name = "Panel_map_1",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = 25,
						relativeToName = "Panel_map_1",
					},
					uipanelviewmodel = 
					{
						Layout="Relative",
						nType = "3"
					},
					visible = "False",
					width = "2772",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_point_1_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "b8c215a4_3789_4fb2_96e8_82b11c7ee9a9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 339,
								PositionY = 327,
								LeftPositon = 292,
								TopPosition = 902,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_2_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "c245878f_16b4_4bc4_b61c_d35c9cce58aa",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 540,
								PositionY = 419,
								LeftPositon = 493,
								TopPosition = 810,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_3_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "d5580a28_ad93_4569_8ebf_0c8f90b4ce36",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 766,
								PositionY = 370,
								LeftPositon = 719,
								TopPosition = 859,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_4_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "c53fe2c9_2bcd_43e6_a790_093ca8366180",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_4",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 858,
								PositionY = 546,
								LeftPositon = 811,
								TopPosition = 683,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_5_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "4a33a8b5_a7eb_40b3_964c_719fe6792664",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 601,
								PositionY = 652,
								LeftPositon = 554,
								TopPosition = 577,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_6_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "2dab155a_fcd7_4e0e_9e4c_8a28b7aa7981",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 828,
								PositionY = 747,
								LeftPositon = 781,
								TopPosition = 482,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_7_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "a0b85ded_84b8_4ae2_9349_1f7810c78de9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_7",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1037,
								PositionY = 639,
								LeftPositon = 990,
								TopPosition = 590,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_8_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "94bc88d3_3257_4aa6_8242_a2ed16e211df",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_8",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1240,
								PositionY = 715,
								LeftPositon = 1193,
								TopPosition = 514,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_9_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "c5a32f3c_9502_4000_9e30_21e2d9a3e11d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1046,
								PositionY = 377,
								LeftPositon = 999,
								TopPosition = 852,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_10_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "56afe02b_eeeb_427c_9423_536a4e891845",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_10",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1275,
								PositionY = 456,
								LeftPositon = 1228,
								TopPosition = 773,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_11_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "877c692b_ff7d_4ef7_a1f3_e97f1f89c775",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_11",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1456,
								PositionY = 363,
								LeftPositon = 1409,
								TopPosition = 866,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_12_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "fef9e79e_3d63_457b_8e3f_660c38f9d93e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_12",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1610,
								PositionY = 508,
								LeftPositon = 1563,
								TopPosition = 721,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_13_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "cf791f98_e080_45f5_b193_751414172bc8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_13",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1775,
								PositionY = 411,
								LeftPositon = 1728,
								TopPosition = 818,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_14_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "3e044056_ece0_43d9_a654_cd7ae179a09a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_14",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1819,
								PositionY = 614,
								LeftPositon = 1772,
								TopPosition = 615,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_15_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "b47273c2_5f3f_4015_a42b_7dfedbe7cb95",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_15",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2000,
								PositionY = 486,
								LeftPositon = 1953,
								TopPosition = 743,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_16_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "38f54607_578e_443e_af0d_f8872027c7d0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_16",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2228,
								PositionY = 403,
								LeftPositon = 2181,
								TopPosition = 826,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_17_Panel_map_1_Panel-tongMap_Layer1_tong_Game",
							UUID = "83a44722_204c_4f94_8d29_020f7e0b986c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_17",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2431,
								PositionY = 514,
								LeftPositon = 2384,
								TopPosition = 715,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_map_2_Panel-tongMap_Layer1_tong_Game",
					UUID = "e78ef4ca_5c52_49d5_a007_654fcaebed33",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "1286",
					ignoreSize = "False",
					name = "Panel_map_2",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = 25,
						relativeToName = "Panel_map_1",
					},
					uipanelviewmodel = 
					{
						Layout="Relative",
						nType = "3"
					},
					width = "2772",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_point_1_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "3dff0d5b_d7e5_4815_8b8c_9992e15d57d3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 339,
								PositionY = 327,
								LeftPositon = 292,
								TopPosition = 902,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_2_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "bebf1fa3_66e1_4ef3_a69d_1d1db8842012",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 540,
								PositionY = 419,
								LeftPositon = 493,
								TopPosition = 810,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_3_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "688dc508_4bc6_4e75_811e_c1528a75bc80",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 766,
								PositionY = 370,
								LeftPositon = 719,
								TopPosition = 859,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_4_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "d262aee2_5862_475e_8201_5c352dc5df08",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_4",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 858,
								PositionY = 546,
								LeftPositon = 811,
								TopPosition = 683,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_5_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "ad0f3ffd_1df7_40cc_af89_7d3c0b7b6a1a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 601,
								PositionY = 652,
								LeftPositon = 554,
								TopPosition = 577,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_6_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "6936851f_146b_460f_a51a_6f67a8fb8315",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 828,
								PositionY = 747,
								LeftPositon = 781,
								TopPosition = 482,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_7_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "da8fc129_df89_4c65_bac3_b60ade5cb0de",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_7",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1037,
								PositionY = 639,
								LeftPositon = 990,
								TopPosition = 590,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_8_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "f824aafe_1ccf_4809_b2e9_f59f8bc4f47e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_8",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1240,
								PositionY = 715,
								LeftPositon = 1193,
								TopPosition = 514,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_9_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "addc0db7_bc07_4989_a27a_9592954489dc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1046,
								PositionY = 377,
								LeftPositon = 999,
								TopPosition = 852,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_10_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "5d5bf830_b6a9_417e_9d54_29c1a5a90d63",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_10",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1275,
								PositionY = 456,
								LeftPositon = 1228,
								TopPosition = 773,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_11_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "350c7e3a_0d83_4b8c_a1ac_096f73713ed3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_11",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1456,
								PositionY = 363,
								LeftPositon = 1409,
								TopPosition = 866,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_12_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "2fd82198_174f_49fc_927a_2a39e76cbfb5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_12",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1610,
								PositionY = 508,
								LeftPositon = 1563,
								TopPosition = 721,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_13_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "acdb8f70_3713_4466_b0b2_c3eaa3b6bbd5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_13",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1775,
								PositionY = 411,
								LeftPositon = 1728,
								TopPosition = 818,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_14_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "2f7585de_8087_42b5_b85f_cf4b920a97c6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_14",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1819,
								PositionY = 614,
								LeftPositon = 1772,
								TopPosition = 615,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_15_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "7f24c8e7_5171_4ab7_a140_8093532baa1a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_15",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2000,
								PositionY = 486,
								LeftPositon = 1953,
								TopPosition = 743,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "panel_point_16_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "771c657a_2f86_4af2_bb8c_ec202dc0121c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "101",
							ignoreSize = "False",
							name = "panel_point_16",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2228,
								PositionY = 403,
								LeftPositon = 2181,
								TopPosition = 826,
								relativeToName = "Panel_map_1",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "94",
							ZOrder = "1",
						},
						{
							controlID = "Panel_tower_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
							UUID = "bea5be88_2bca_445d_b4d9_59ec2fd5b669",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "150",
							ignoreSize = "False",
							name = "Panel_tower",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 1434,
								PositionY = 705,
								LeftPositon = 1379,
								TopPosition = 500,
								relativeToName = "Panel_map_2",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Spine_tower_Panel_tower_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
									UUID = "156b5caa_9499_4bec_85b8_c0b17186ed43",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_tower",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/VITmax_effect_level_boss",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 15,
									},
									ZOrder = "1",
								},
								{
									controlID = "LoadingBar_boss_Panel_tower_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
									UUID = "27e852cf_c015_4b0f_bb26_abacf5428d00",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MELoadingBar",
									direction = "5",
									dstBlendFunc = "771",
									height = "124",
									ignoreSize = "True",
									name = "LoadingBar_boss",
									percent = "75",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texture = "ui/tong/map/bar.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 17,
									},
									width = "124",
									ZOrder = "1",
								},
								{
									controlID = "Panel_effect_Panel_tower_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
									UUID = "165233a9_2e89_41b0_8954_a61629cf58b9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "110",
									ignoreSize = "False",
									name = "Panel_effect",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 18,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_point_Panel_effect_Panel_tower_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
											UUID = "018a8e11_de37_4894_ac7a_ba66c2399c31",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "10",
											ignoreSize = "False",
											name = "Panel_point",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 44,
												PositionY = 12,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "10",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Spine_point_Panel_point_Panel_effect_Panel_tower_Panel_map_2_Panel-tongMap_Layer1_tong_Game",
													UUID = "b7cd68ff_5103_4345_88e5_5f61c64ef871",
													classname = "MESpine",
													dstBlendFunc = "771",
													name = "Spine_point",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													spineModel = 
													{
														SpinePath = "effect/effects_kabala_erodeflame1/effects_kabala_erodeflame1",
														animationName = "animation",
														IsLoop = true,
														IsPlay = true,
														IsUseQueue = false,
														AnimationQueue = 
														{
															
														},
													},
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "front_Panel-tongMap_Layer1_tong_Game",
					UUID = "a2fd5e44_c8cd_4e9d_b61a_d62473e923d3",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "front",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_tongMapCloud_a1_front_Panel-tongMap_Layer1_tong_Game",
							UUID = "e0fceaf6_09f2_4645_9143_9d685d591cb0",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMapCloud_a1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloud_01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 256,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMapCloud_a3_front_Panel-tongMap_Layer1_tong_Game",
							UUID = "80647ab7_ca83_4953_a6a5_f80ecdb5778a",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "1024",
							ignoreSize = "True",
							name = "Image_tongMapCloud_a3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloud_03.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2048,
								PositionY = 256,
							},
							width = "724",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMapCloud_a4_front_Panel-tongMap_Layer1_tong_Game",
							UUID = "4d55e2f1_9a69_4e5f_9e93_54763de2f585",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "256",
							ignoreSize = "True",
							name = "Image_tongMapCloud_a4",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloud_04.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMapCloud_a5_front_Panel-tongMap_Layer1_tong_Game",
							UUID = "3d75ed7b_439f_4e2a_a43c_bdc2bba17987",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "256",
							ignoreSize = "True",
							name = "Image_tongMapCloud_a5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloud_05.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1024,
							},
							width = "1024",
							ZOrder = "1",
						},
						{
							controlID = "Image_tongMapCloud_a6_front_Panel-tongMap_Layer1_tong_Game",
							UUID = "447127ad_527d_47a3_a8f2_98141dc4f21e",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "256",
							ignoreSize = "True",
							name = "Image_tongMapCloud_a6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "fightmap/event_VITmax/cloud_06.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2048,
							},
							width = "724",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"fightmap/event_VITmax/bg.png",
			"fightmap/event_VITmax/cloudBg_01.png",
			"fightmap/event_VITmax/cloudBg_02.png",
			"fightmap/event_VITmax/cloudBg_03.png",
			"fightmap/event_VITmax/map_01.png",
			"fightmap/event_VITmax/map_02.png",
			"fightmap/event_VITmax/map_03.png",
			"fightmap/event_VITmax/map_04.png",
			"fightmap/event_VITmax/map_05.png",
			"fightmap/event_VITmax/map_06.png",
			"ui/tong/map/bar.png",
			"fightmap/event_VITmax/cloud_01.png",
			"fightmap/event_VITmax/cloud_03.png",
			"fightmap/event_VITmax/cloud_04.png",
			"fightmap/event_VITmax/cloud_05.png",
			"fightmap/event_VITmax/cloud_06.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

