local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-tongMainView_Layer1_tong_Game",
			UUID = "4ed89e07_bdf1_40a5_a522_ca28de99ae59",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "89",
			sizepercenty = "110",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_ui_Panel-tongMainView_Layer1_tong_Game",
					UUID = "778759dd_9b11_4361_9b39_e7cef9231685",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#59F5C9CC;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_ui",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "ScrollView_map_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "ef359d12_4bc4_4f9b_b453_0fc5867783e0",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "3",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							innerHeight = "640",
							innerWidth = "1136",
							name = "ScrollView_map",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -568,
								PositionY = -320,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
						},
						{
							controlID = "Panel_firstMap_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "51c67647_a480_48b3_9c63_a52dcea962bb",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "400",
							ignoreSize = "False",
							name = "Panel_firstMap",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "400",
							ZOrder = "1",
						},
						{
							controlID = "Button_airDrop_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "86dad2a2_87b7_4106_8d0f_f9f2e505cf6b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "106",
							ignoreSize = "True",
							name = "Button_airDrop",
							normal = "ui/tong/map/info/008.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 459,
								PositionY = -222,
							},
							UItype = "Button",
							width = "215",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_ariDropRefresh_Button_airDrop_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "870480aa_0c18_498e_ba9c_3e23f6b6aa66",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_ariDropRefresh",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "进行补给",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										LeftPositon = 9,
										TopPosition = 19,
										relativeToName = "Panel_fight_info",
									},
									visible = "False",
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "cb952f9f_bb58_498c_9913_2ebbddc72d1c",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "450",
							ignoreSize = "True",
							name = "Image_info_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/map/info/0000000.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 557,
								PositionY = -53,
								LeftPositon = 1138,
								TopPosition = 172,
								relativeToName = "Panel_fight_info",
							},
							width = "366",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_nextFreashTime_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "e62179b4_ecce_4cdd_9e45_9b196784b7a0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF097583",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_nextFreashTime",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "距离下次补给：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 52,
										PositionY = 153,
										LeftPositon = 9,
										TopPosition = 19,
										relativeToName = "Panel_fight_info",
									},
									width = "143",
									ZOrder = "1",
								},
								{
									controlID = "Label_nextCount_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "522e1f30_ce1e_41cf_9d37_74c74a331cdf",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF097583",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_nextCount",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "下次补给数量：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 52,
										PositionY = 92,
										LeftPositon = 9,
										TopPosition = 19,
										relativeToName = "Panel_fight_info",
									},
									width = "143",
									ZOrder = "1",
								},
								{
									controlID = "Label_threat_level_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "0bf61b10_f862_44f7_88f0_2a5ea08aa661",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF097583",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_threat_level",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "当前威胁等级：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 52,
										PositionY = 27,
										LeftPositon = 9,
										TopPosition = 19,
										relativeToName = "Panel_fight_info",
									},
									width = "143",
									ZOrder = "1",
								},
								{
									controlID = "Label_elitePoint_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "f2d02f18_7cc3_46f7_b566_4157a1e26408",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF097583",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_elitePoint",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "精英反应点数：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 52,
										PositionY = -36,
										LeftPositon = 9,
										TopPosition = 19,
										relativeToName = "Panel_fight_info",
									},
									width = "143",
									ZOrder = "1",
								},
								{
									controlID = "Button_skill_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "12403be6_7d8a_4f1a_8977_b23d635b6844",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_skill",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 110,
										PositionY = -139,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMainView_1_Button_skill_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
											UUID = "0a99119a_5fd9_439f_a72a_180298523f96",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_tongMainView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "技能",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "51",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_helpList_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "fb478dc8_c509_4a30_87de_88d03b1b2ace",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_helpList",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 262,
										PositionY = -139,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMainView_1_Button_helpList_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
											UUID = "7c7468f5_e11a_44d3_94cd_ecb4a20e1517",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_tongMainView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "支援信号",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "99",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_fight_info_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "c0007bf7_0fc3_4604_9060_cb20ca199d21",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "94",
									ignoreSize = "True",
									name = "Button_fight_info",
									normal = "ui/tong/map/info/002.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -9,
										PositionY = 5,
									},
									UItype = "Button",
									width = "66",
									ZOrder = "1",
								},
								{
									controlID = "Image_tongMainView_1_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "8ba440df_5fe1_4831_b2f9_6e665f4e34a0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "5",
									ignoreSize = "True",
									name = "Image_tongMainView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/map/info/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 182,
										PositionY = 124,
									},
									width = "279",
									ZOrder = "1",
								},
								{
									controlID = "Image_tongMainView_1-Copy1_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "4587725e_faa5_4367_9006_ac173a772f6a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "5",
									ignoreSize = "True",
									name = "Image_tongMainView_1-Copy1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/map/info/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 182,
										PositionY = 60,
									},
									width = "279",
									ZOrder = "1",
								},
								{
									controlID = "Image_tongMainView_1-Copy2_Image_info_bg_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "e2c6eba4_6423_4310_8512_3bcd33db9bcc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "5",
									ignoreSize = "True",
									name = "Image_tongMainView_1-Copy2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/map/info/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 182,
										PositionY = -2,
									},
									width = "279",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Spine_elite_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "157b01b0_0c41_477e_a5bd_e4047097c230",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_elite",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/eff_vitmax/eff_map/hit_elite/VITmax_effect_hint_elite",
								animationName = "action1",
								IsLoop = false,
								IsPlay = false,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							ZOrder = "1",
						},
						{
							controlID = "Spine_supply_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "c247665d_50d6_416c_b3d5_cf256ae32a81",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_supply",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/eff_vitmax/eff_map/hint_supply/VITmax_effect_hint_supply",
								animationName = "action1",
								IsLoop = false,
								IsPlay = false,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							ZOrder = "1",
						},
						{
							controlID = "Panel_mask_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "21bb8404_0057_4d16_bc57_621455544a72",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "400",
							ignoreSize = "False",
							name = "Panel_mask",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "400",
							ZOrder = "1",
						},
						{
							controlID = "Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
							UUID = "c9a3efd8_9b92_476e_a602_d3226d456f52",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "80",
							ignoreSize = "False",
							name = "Panel_type",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 388,
								PositionY = 212,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "320",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_map1_Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "2efec177_abef_45d9_b183_e7621c0b97a5",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Button_map1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -79,
										PositionY = -1,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_normal_Button_map1_Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
											UUID = "68173c8c_9d43_4072_b7c0_1ad8274f9058",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "85",
											ignoreSize = "True",
											name = "Image_normal",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/info/007.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "170",
											ZOrder = "1",
										},
										{
											controlID = "Image_select_Button_map1_Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
											UUID = "658eca1d_d50b_4662_ab90_ff75ae14cee0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "85",
											ignoreSize = "True",
											name = "Image_select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/info/004.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "170",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_map2_Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
									UUID = "35b94ac0_369a_45f6_b844_ed5937ded49b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Button_map2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 81,
										PositionY = -1,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_normal_Button_map2_Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
											UUID = "fc4e0dfe_1dc8_4b31_a695_f4b9a22bf906",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "85",
											ignoreSize = "True",
											name = "Image_normal",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/info/006.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "170",
											ZOrder = "1",
										},
										{
											controlID = "Image_select_Button_map2_Panel_type_Panel_ui_Panel-tongMainView_Layer1_tong_Game",
											UUID = "f9fd6ef0_e30b_4a31_8e15_88925089d649",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "85",
											ignoreSize = "True",
											name = "Image_select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/info/005.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "170",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
					UUID = "7eb420a4_2b43_4458_9658_2642a8121cb8",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = -641,
						BottomPosition = -641,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
							UUID = "039d0f91_c1f9_4431_9706_fa7cd75253fc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFFA500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "150",
							ignoreSize = "False",
							name = "panel_point",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 161,
								PositionY = 176,
								LeftPositon = 242,
								TopPosition = 752,
								relativeToName = "Panel_map_1",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "150",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_airdrop_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
									UUID = "27c1ae38_801f_4789_91d1_a9dca42d94e7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "150",
									ignoreSize = "False",
									name = "Image_airdrop",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "150",
									ZOrder = "1",
								},
								{
									controlID = "Image_monster_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
									UUID = "edd50052_775e_40e3_ad8d_6d6c88ce49fb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "150",
									ignoreSize = "False",
									name = "Image_monster",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "150",
									ZOrder = "1",
								},
								{
									controlID = "Image_normal_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
									UUID = "413dbda1_34a1_4bb6_88ec_8abe044b76f3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "150",
									ignoreSize = "False",
									name = "Image_normal",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_fight_Image_normal_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
											UUID = "f323e05d_3303_4727_b67e_8eb64d504bc1",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "161",
											ignoreSize = "True",
											name = "Image_fight",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "126",
											ZOrder = "1",
										},
										{
											controlID = "Image_dating_Image_normal_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
											UUID = "4405d6a0_fa71_475c_a821_46b487a99b4c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "161",
											ignoreSize = "True",
											name = "Image_dating",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "126",
											ZOrder = "1",
										},
										{
											controlID = "Label_tag_normal_Image_normal_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
											UUID = "a038986e_e2cd_45b7_81bf_2ed510eeea8d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF44B7DA",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_tag_normal",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "EP 1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -83,
											},
											width = "45",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_normal_s_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
									UUID = "239b2e9b_566b_4701_976e_07d434829fa2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "150",
									ignoreSize = "False",
									name = "Image_normal_s",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_icon_Image_normal_s_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
											UUID = "78b08214_7a06_4be9_a0f5_ba2c6829d185",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "101",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/map/003.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -21,
											},
											width = "94",
											ZOrder = "1",
										},
										{
											controlID = "Label_tag_Image_normal_s_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
											UUID = "230d6214_4b5a_4c3a_8920_fb2a34b453f4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF44B7DA",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_tag",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "EP 1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -83,
											},
											width = "45",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_mask_panel_point_Panel_prefab_Panel-tongMainView_Layer1_tong_Game",
									UUID = "eca701ae_1d2d_4b18_9320_0dd1c0eafa68",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_mask",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/effect_DW_mainScene/evt_DW2020_mainScene",
										animationName = "fort_disapear",
										IsLoop = false,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 9,
										PositionY = -59,
									},
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/tong/map/info/008.png",
			"ui/tong/map/info/0000000.png",
			"ui/tong/common/btn1.png",
			"ui/tong/map/info/002.png",
			"ui/tong/map/info/001.png",
			"ui/tong/map/info/007.png",
			"ui/tong/map/info/004.png",
			"ui/tong/map/info/006.png",
			"ui/tong/map/info/005.png",
			"ui/tong/map/001.png",
			"ui/tong/map/002.png",
			"ui/tong/map/003.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

