local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-tongBossView_Layer1_tong_Game",
			UUID = "85d40922_941e_4c14_9aea_47a116d65981",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-tongBossView_Layer1_tong_Game",
					UUID = "b4e56066_8834_436a_82e0_ece1933ab18b",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "ce1e62c1_e7a2_4d7d_8586_1ef958aaeb5b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/tong/common/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Spine_tongBossView_1_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "f02cdbac_6fe1_4c01_8249_cced28141399",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_tongBossView_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/eff_vitmax/ui_boss/boss_paint/VITmax_effect_boss",
								animationName = "idle",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -195,
								PositionY = -9,
							},
							ZOrder = "1",
						},
						{
							controlID = "ScrollView_report_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "ddf643de_de2d_45b5_a684_d6687a9fd238",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "75",
							ignoreSize = "False",
							innerHeight = "75",
							innerWidth = "338",
							name = "ScrollView_report",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -336,
								PositionY = -69,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "338",
							ZOrder = "1",
						},
						{
							controlID = "Button_award_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "c3b41f97_328d_4a32_a6bc_197fe0976bee",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "81",
							ignoreSize = "True",
							name = "Button_award",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/boss/006.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -459,
								PositionY = -199,
							},
							width = "137",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_percent_info_Button_award_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "cee17f37_4816_4081_81a0_1bde272da6fd",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF98109E",
										StrokeSize = 2,
									},
									height = "31",
									ignoreSize = "True",
									name = "Label_percent_info",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "HP Left",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -48,
										PositionY = -31,
									},
									width = "79",
									ZOrder = "1",
								},
								{
									controlID = "Label_percent_Button_award_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "5e6b4aa6_ae9a_41a6_bdc1_40448a9826eb",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF98109E",
										StrokeSize = 2,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_percent",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "500%",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 65,
										PositionY = -34,
									},
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_bar_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "5de9d3e4_8ecb_482d_9a34_0d6e6bcb9a49",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "10",
							ignoreSize = "False",
							name = "Image_bar",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/boss/bar2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -79,
								PositionY = -238,
							},
							width = "420",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "LoadingBar_Image_bar_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "4e8d9756_60d9_411b_a495_b6cffcdca91b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MELoadingBar",
									direction = "0",
									dstBlendFunc = "771",
									height = "10",
									ignoreSize = "False",
									name = "LoadingBar",
									percent = "42",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texture = "ui/tong/boss/bar1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "420",
									ZOrder = "1",
								},
								{
									controlID = "Panel_spineBg_Image_bar_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "9e1ac871_922a_4904_97ed_0e1e709cd562",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "False",
									name = "Panel_spineBg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -318,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									visible = "False",
									width = "640",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Spine_bar_Panel_spineBg_Image_bar_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "b287e984_9adf_4f18_b3ca_887f0724de87",
											classname = "MESpine",
											dstBlendFunc = "771",
											name = "Spine_bar",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											spineModel = 
											{
												SpinePath = "effect/chronoBar/chronoBar",
												animationName = "animation",
												IsLoop = true,
												IsPlay = true,
												IsUseQueue = false,
												AnimationQueue = 
												{
													
												},
											},
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 320,
												PositionY = -1,
												LeftPositon = 466,
												TopPosition = 600,
												relativeToName = "Panel",
											},
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_point_Image_bar_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "f6482145_6e06_4044_bb2a_dc720b7b4a7f",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_point",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_boss/bar/VITmax_effect_boss_bar",
										animationName = "bar",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -210,
										LeftPositon = 910,
										TopPosition = -51,
										relativeToName = "Panel",
									},
									ZOrder = "1",
								},
								{
									controlID = "Spine_light_Image_bar_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "87d41310_c222_4cb2_b83a_52c9f498ef15",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_light",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/chronoLight/chronoLight",
										animationName = "animation",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -1,
										LeftPositon = 322,
										TopPosition = 227,
										relativeToName = "Panel",
									},
									visible = "False",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "b90ba2f9_4721_4d89_a992_0744d500703d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "480",
							ignoreSize = "False",
							name = "Image_info_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 327,
								PositionY = -21,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "400",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_dress_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "c7aee189_ce75_4e29_a9eb_ebdf5fb8a061",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "11",
									ignoreSize = "True",
									name = "Image_dress",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/boss/dressline.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 2,
										PositionY = 181,
									},
									width = "350",
									ZOrder = "1",
								},
								{
									controlID = "Panel_rankItem1_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "61697910_c23d_4bc0_bf99_da4b00ee06d3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_rankItem1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 9,
										PositionY = 139,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "338",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rank_icon_Panel_rankItem1_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "3f4cba6b_697e_4d11_aefe_0ae6ebc9f741",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "53",
											ignoreSize = "True",
											name = "Image_rank_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/boss/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -138,
											},
											width = "73",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Panel_rankItem1_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "019ea8fd_61cd_422c_bf78_93596f96389f",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF398C95",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Player name",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 153,
												PositionY = -13,
											},
											width = "118",
											ZOrder = "1",
										},
										{
											controlID = "Label_hurt_Panel_rankItem1_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "d79edc89_2e08_4de3_8e36_e7a7fb34821b",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF398C95",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_hurt",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "8888",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 153,
												PositionY = 18,
											},
											width = "49",
											ZOrder = "1",
										},
										{
											controlID = "Image_split_Panel_rankItem1_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "d00a8bf2_2525_4a1e_9723_494d87953934",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "5",
											ignoreSize = "True",
											name = "Image_split",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/boss/split.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = -40,
											},
											width = "344",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_rankItem2_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "ac1b12f9_bdc2_49c8_951f_e1d63507793e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_rankItem2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 8,
										PositionY = 60,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "338",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rank_icon_Panel_rankItem2_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "75e690b9_5aed_45cf_bcd3_ba261fa738a4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "45",
											ignoreSize = "True",
											name = "Image_rank_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/boss/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -138,
											},
											width = "58",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Panel_rankItem2_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "0f585b8d_a773_4fe1_b98f_ac883351565a",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF398C95",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Player name",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 153,
												PositionY = -13,
											},
											width = "118",
											ZOrder = "1",
										},
										{
											controlID = "Label_hurt_Panel_rankItem2_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "0ae00797_e14f_4502_b611_9c66668292d4",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF398C95",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_hurt",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "8888",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 153,
												PositionY = 17,
											},
											width = "49",
											ZOrder = "1",
										},
										{
											controlID = "Image_split_Panel_rankItem2_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "d4eeeba8_2daa_41b8_a0ef_7046b3360f19",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "5",
											ignoreSize = "True",
											name = "Image_split",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/boss/split.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = -40,
											},
											width = "344",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_rankItem3_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "233b021f_c132_444d_b7cc_fe6f70e037cf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_rankItem3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 7,
										PositionY = -18,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "338",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rank_icon_Panel_rankItem3_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "6b87b676_d144_4c1a_b6ac_2b6bc14f1319",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "35",
											ignoreSize = "True",
											name = "Image_rank_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/boss/003.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -138,
											},
											width = "48",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Panel_rankItem3_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "15039834_d61b_41f2_a68e_6bc0c5d9a730",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF398C95",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Player name",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 153,
												PositionY = -13,
											},
											width = "118",
											ZOrder = "1",
										},
										{
											controlID = "Label_hurt_Panel_rankItem3_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "e05cba0e_5e9f_4d08_b2fd_4a5bcee33ffe",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF398C95",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_hurt",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "8888",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 154,
												PositionY = 19,
											},
											width = "49",
											ZOrder = "1",
										},
										{
											controlID = "Image_split_Panel_rankItem3_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "552844d3_fd46_41ee_b25c_37d06c78c02f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "5",
											ignoreSize = "True",
											name = "Image_split",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/boss/split.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -4,
												PositionY = -39,
											},
											width = "344",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_info_title_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "4cf82ca4_6814_4ba1_beb4_9a03b5e0c5f4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF126280",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "28",
									ignoreSize = "True",
									name = "Label_info_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Rank",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 205,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
									UUID = "46ad9c9b_7e8d_4bb7_8085_a253cde9848b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "83",
									ignoreSize = "False",
									name = "Image_single",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 15,
										PositionY = -186,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "334",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_sigle_hurt_Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "d98fde4c_984c_4c81_8dfe_90152fc6249c",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "28",
											ignoreSize = "True",
											name = "Label_sigle_hurt",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "888888",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -174,
												PositionY = 70,
											},
											width = "81",
											ZOrder = "1",
										},
										{
											controlID = "Label_tip_Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "a7bb84c4_757b_4410_8b54_ab5b7d3d1419",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_tip",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "My DMG",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -170,
												PositionY = 103,
											},
											width = "96",
											ZOrder = "1",
										},
										{
											controlID = "Button_rank_Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "11fd3c7d_36ed_4648_a936_f1561cc3d8d7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "True",
											name = "Button_rank",
											normal = "ui/tong/boss/004.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 128,
												PositionY = 81,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Label_blood_tip_Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "07809ea7_cea0_4a9d_99c8_1d8d06215c6c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_blood_tip",
											nTextAlign = "1",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Enter the next stage after HP is reduced to 75% below",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -31,
												PositionY = -27,
											},
											width = "265",
											ZOrder = "1",
										},
										{
											controlID = "Label_tongBossView_1_Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "8d900286_cc03_4858_a94f_0fe02edaabeb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_tongBossView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Current Threat Level Cap",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -34,
												PositionY = 2,
											},
											width = "247",
											ZOrder = "1",
										},
										{
											controlID = "Label_max_lv_Image_single_Image_info_bg_Panel_root_Panel-tongBossView_Layer1_tong_Game",
											UUID = "32407966_7ce8_477b_8ca9_727242226571",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "50",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "57",
											ignoreSize = "True",
											name = "Label_max_lv",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "9",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 124,
												PositionY = -13,
											},
											width = "29",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_report_Panel_root_Panel-tongBossView_Layer1_tong_Game",
							UUID = "4b7f01e1_279e_4354_aa77_71fde603b750",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "450",
							ignoreSize = "False",
							name = "Panel_report",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -500,
								PositionY = -230,
								LeftPositon = 636,
								TopPosition = -219,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "600",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
					UUID = "b7b22770_ceb0_400c_8da3_a20200b5e757",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = -442,
						TopPosition = 762,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_rankItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
							UUID = "9b69893b_d531_46f7_b033_4f264ae57e0b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "60",
							ignoreSize = "False",
							name = "Panel_rankItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -231,
								PositionY = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "338",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_rank_icon_Panel_rankItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "1d424c4b_34df_4cf1_b51c_9d1d55f56078",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "Image_rank_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/assist/038.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -128,
									},
									width = "52",
									ZOrder = "1",
								},
								{
									controlID = "Label_rank_num_Panel_rankItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "186453d9_9da6_416d_9e49_28ef4ae2da19",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_rank_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "543",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -132,
									},
									width = "44",
									ZOrder = "1",
								},
								{
									controlID = "Label_name_Panel_rankItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "a1f481fc_0148_4147_b277_074479dd4d28",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Player name",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -34,
									},
									width = "98",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_bg_Panel_rankItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "deb81a33_4863_44e6_9871_02f25036a672",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "104",
									ignoreSize = "True",
									name = "Image_icon_bg",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/playerInfo/avatar/TXBK_moren_0.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -68,
									},
									width = "104",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_rankItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "9bd2543c_cdf3_402c_ad79_4188191a7090",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "98",
									ignoreSize = "True",
									name = "Image_icon",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/hero/name/1101011.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -68,
									},
									width = "98",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_reportItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
							UUID = "489bda08_2c99_4145_a885_340dbb5c96a7",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "1",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "32",
							ignoreSize = "False",
							name = "Panel_reportItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -12,
								PositionY = -106,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "422",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_text_bg_Panel_reportItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "5821e4e8_e0cf_4228_a62d_aaa99b032ce9",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "32",
									ignoreSize = "True",
									name = "Image_text_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/boss/textbg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "422",
									ZOrder = "1",
								},
								{
									controlID = "Label_report_Panel_reportItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "73f917a4_89a2_4b9a_b0c0_3092e44fde92",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#00FFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "18",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "21",
									ignoreSize = "False",
									name = "Label_report",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Player name",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 8,
										PositionY = -17,
									},
									width = "0",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
							UUID = "90ce6897_f2f3_4e8d_bf9b_a9d24dc19215",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "80",
							ignoreSize = "False",
							name = "Panel_awardItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -119,
								PositionY = 168,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "91",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_arrow_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "1c2192fe_0c04_4dd6_bef1_46bfdc556d67",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "96",
									ignoreSize = "True",
									name = "Image_arrow",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/boss/007.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -4,
									},
									width = "91",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_item_Image_arrow_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
											UUID = "86ab565e_e3c7_4108_9a2a_dd8cd2f6530a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_item",
											scaleX = "0.45",
											scaleY = "0.45",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/510106.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 14,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_geted_Image_arrow_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
											UUID = "a9571ddd_be83_429a_91c2_843439c52005",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#47126280",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_geted",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Claimed",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -18,
											},
											width = "66",
											ZOrder = "1",
										},
										{
											controlID = "Label_get_Image_arrow_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
											UUID = "b575e005_a64b_4677_93b7_84e1925b63a0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#47126280",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_get",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Claimable",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -18,
											},
											width = "78",
											ZOrder = "1",
										},
										{
											controlID = "Label_not_Image_arrow_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
											UUID = "4a02d5ab_25dc_4ec3_8bbf_2f09af6197e9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "15",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#47126280",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_not",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Not Achieved",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -18,
											},
											width = "70",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_num_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "31e241ab_55ab_4a60_9d68_0c89ad8a9320",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "18",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "21",
									ignoreSize = "True",
									name = "Label_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "45%",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -58,
									},
									visible = "False",
									width = "34",
									ZOrder = "1",
								},
								{
									controlID = "Image_dot_Panel_awardItem_Panel_prefab_Panel-tongBossView_Layer1_tong_Game",
									UUID = "8cf683b1_ec42_4f09_9ffd_04e8250d8385",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "True",
									name = "Image_dot",
									scaleX = "0.6",
									scaleY = "0.6",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/boss/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 1,
										PositionY = -63,
									},
									width = "34",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/tong/common/bg.png",
			"ui/tong/boss/006.png",
			"ui/tong/boss/bar2.png",
			"ui/tong/boss/bar1.png",
			"ui/tong/boss/dressline.png",
			"ui/tong/boss/001.png",
			"ui/tong/boss/split.png",
			"ui/tong/boss/002.png",
			"ui/tong/boss/003.png",
			"ui/tong/boss/004.png",
			"ui/activity/assist/038.png",
			"ui/playerInfo/avatar/TXBK_moren_0.png",
			"icon/hero/name/1101011.png",
			"ui/tong/boss/textbg.png",
			"ui/tong/boss/007.png",
			"icon/item/goods/510106.png",
			"ui/tong/boss/008.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

