local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-tongMonsterView_Layer1_tong_Game",
			UUID = "3441d4d6_47a2_4f9c_8c40_d6ad1f42b280",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
					UUID = "3ba8d3c4_1fa6_4a9f_9743_2502ec794c1f",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 693,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1386",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
							UUID = "5f452228_ac88_463b_a6cd_ace4326147f0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "574",
							ignoreSize = "True",
							name = "Image_left_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/elite/left.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -234,
								PositionY = 301,
							},
							width = "600",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "00005fc4_3238_45fb_9f5b_e9cb296fea5f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "88",
									ignoreSize = "True",
									name = "Image_name",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/elite/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -190,
										PositionY = 199,
									},
									width = "197",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_monsterName_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "d0d2c540_01e4_4edd_bfc3_2e89742020e0",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFD1F8FF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "28",
											ignoreSize = "True",
											name = "Label_monsterName",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Maple",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -84,
												PositionY = 16,
											},
											width = "79",
											ZOrder = "1",
										},
										{
											controlID = "Panel_threat_level_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "9fd95504_87df_4107_bb8c_dd4b194a9af4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "88",
											ignoreSize = "False",
											name = "Panel_threat_level",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "197",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_ttitle_Panel_threat_level_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "65d8c4bf_0d3e_40f4_a3f8_609a53024d03",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF05383F",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "25",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "29",
													ignoreSize = "True",
													name = "Label_ttitle",
													nTextAlign = "1",
													nTextHAlign = "1",
													scaleX = "0.6",
													scaleY = "0.6",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Threat Level",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -86,
														PositionY = -17,
													},
													width = "164",
													ZOrder = "1",
												},
												{
													controlID = "Image_level_Panel_threat_level_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "21f2e9fa_7e02_43aa_b02e_5a3b5d237fc2",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "70",
													ignoreSize = "True",
													name = "Image_level",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/tong/squad/barbg.png",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 52,
														PositionY = 2,
													},
													width = "70",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "LoadingBar_level_Image_level_Panel_threat_level_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "93f6b6c7_a575_47c6_bdc3_687e9a818d7d",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MELoadingBar",
															direction = "4",
															dstBlendFunc = "771",
															height = "70",
															ignoreSize = "True",
															name = "LoadingBar_level",
															percent = "0",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texture = "ui/tong/squad/bar1.png",
															touchAble = "True",
															UILayoutViewModel = 
															{
																LeftPositon = 838,
																TopPosition = 189,
																relativeToName = "Panel",
															},
															width = "70",
															ZOrder = "1",
															components = 
															{
																
																{
																	controlID = "Label_level_LoadingBar_level_Image_level_Panel_threat_level_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
																	UUID = "199eb596_1e31_4b6f_a191_6f4b39bf8ce8",
																	anchorPoint = "False",
																	anchorPointX = "0.5",
																	anchorPointY = "0.5",
																	classname = "MELabel",
																	compPath = "luacomponents.common.MEIconLabel",
																	dstBlendFunc = "771",
																	FontColor = "#FFD1F8FF",
																	fontName = "font/MFLiHei_Noncommercial.ttf",
																	fontShadow = 
																	{
																		IsShadow = false,
																		ShadowColor = "#FFFFFFFF",
																		ShadowAlpha = 255,
																		OffsetX = 0,
																		OffsetY = 0,
																	},
																	fontSize = "40",
																	fontStroke = 
																	{
																		IsStroke = false,
																		StrokeColor = "#FFE6E6E6",
																		StrokeSize = 1,
																	},
																	height = "46",
																	ignoreSize = "True",
																	name = "Label_level",
																	nTextAlign = "1",
																	nTextHAlign = "1",
																	sizepercentx = "0",
																	sizepercenty = "0",
																	sizeType = "0",
																	srcBlendFunc = "770",
																	text = "42",
																	touchAble = "False",
																	touchScaleEnable = "False",
																	UILayoutViewModel = 
																	{
																		PositionY = -5,
																	},
																	width = "45",
																	ZOrder = "1",
																},
																{
																	controlID = "Label_difficulty_LoadingBar_level_Image_level_Panel_threat_level_Image_name_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
																	UUID = "b62bfa4b_0fdb_4c8e_b099_116157c65de8",
																	anchorPoint = "False",
																	anchorPointX = "0.5",
																	anchorPointY = "0.5",
																	classname = "MELabel",
																	compPath = "luacomponents.common.MEIconLabel",
																	dstBlendFunc = "771",
																	FontColor = "#FFD1F8FF",
																	fontName = "font/MFLiHei_Noncommercial.ttf",
																	fontShadow = 
																	{
																		IsShadow = false,
																		ShadowColor = "#FFFFFFFF",
																		ShadowAlpha = 255,
																		OffsetX = 0,
																		OffsetY = 0,
																	},
																	fontSize = "40",
																	fontStroke = 
																	{
																		IsStroke = false,
																		StrokeColor = "#FFE6E6E6",
																		StrokeSize = 1,
																	},
																	height = "46",
																	ignoreSize = "True",
																	name = "Label_difficulty",
																	nTextAlign = "1",
																	nTextHAlign = "1",
																	sizepercentx = "0",
																	sizepercenty = "0",
																	sizeType = "0",
																	srcBlendFunc = "770",
																	text = "42",
																	touchAble = "False",
																	touchScaleEnable = "False",
																	UILayoutViewModel = 
																	{
																		PositionY = -5,
																	},
																	width = "45",
																	ZOrder = "1",
																},
															},
														},
													},
												},
											},
										},
									},
								},
								{
									controlID = "Image_monster_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "a179757e_0d50_4e63_acb9_76edd020779c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_monster",
									scaleX = "0.64",
									scaleY = "0.64",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 10,
										PositionY = -360,
									},
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Image_bornEffect_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "3f4a4b64_0b03_4502_a61f_1aacc7365803",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_bornEffect",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -3,
										PositionY = -291,
									},
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "627196c3_2788_448d_94f0_71e24b7187ef",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "579",
									ignoreSize = "True",
									name = "Image_info_view",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/elite/bg.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 517,
										PositionY = -10,
									},
									width = "517",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_tongMonsterView_1_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "a8a3e9d9_feb6_468d_b50f_70a0330e0741",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "35",
											ignoreSize = "False",
											name = "Image_tongMonsterView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/elite/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 225,
											},
											width = "380",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_buff_tip_Image_tongMonsterView_1_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "f652f71a_6639_4d9d_bcdb_b5be4d1498d2",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF126280",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_buff_tip",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Threat Factor activated",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = -2,
													},
													width = "269",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Label_special_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "d76bff76_60c7_476a_8083_bfac34c53049",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_special",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Fearless Mode",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 192,
											},
											width = "129",
											ZOrder = "1",
										},
										{
											controlID = "Label_nil_buff_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "20f976cc_82a9_4817_bb6b_2f923eb83bad",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF126280",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_nil_buff",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "No Threat Factors for the current level of difficulty",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -1,
												PositionY = 99,
											},
											width = "409",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_buff_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "9abb127b_e53f_4b74_b4aa_382c5710a3a0",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "2",
											dstBlendFunc = "771",
											height = "140",
											ignoreSize = "False",
											innerHeight = "140",
											innerWidth = "420",
											name = "ScrollView_buff",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -188,
												PositionY = 33,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "420",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_buff_big_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "5a6e9ab2_3870_4f62_b17a_a5f76f1df112",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FF008080;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "2",
											dstBlendFunc = "771",
											height = "140",
											ignoreSize = "False",
											innerHeight = "140",
											innerWidth = "420",
											name = "ScrollView_buff_big",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionY = 33,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "420",
											ZOrder = "1",
										},
										{
											controlID = "Image_nil_award_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "482d90af_6005_42af_bd16_ab546fe3c958",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "123",
											ignoreSize = "False",
											name = "Image_nil_award",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/elite/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -100,
											},
											width = "380",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_nil_award_Image_nil_award_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "a20a11b4_9a13_4d95_bfb3_5969e9556ebe",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF126280",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "23",
													ignoreSize = "True",
													name = "Label_nil_award",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Battle not started, unable to get rewards",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -2,
														PositionY = 56,
													},
													width = "314",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "f1e2849e_9e83_468d_bc6a_d5612a6e0a03",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "123",
											ignoreSize = "False",
											name = "Panel_reward",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -209,
												PositionY = -101,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "420",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Panel_cur_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "a5857c33_eb66_43c9_acd6_0c1597c37bd2",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "123",
													ignoreSize = "False",
													name = "Panel_cur_reward",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "206",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_bg_Panel_cur_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "c8aab7fb_08f9_4fcd_b3f6_8054f8053c51",
															anchorPoint = "False",
															anchorPointX = "0",
															anchorPointY = "0",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "123",
															ignoreSize = "True",
															name = "Image_bg",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/tong/elite/002.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "206",
															ZOrder = "1",
														},
														{
															controlID = "Label_cur_tip_Panel_cur_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "dc6bb187_ea49_4750_a650_3c60ce732679",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF126280",
															fontName = "font/MFLiHei_Noncommercial.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_cur_tip",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "Aktuelle Belohnung",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionX = 113,
																PositionY = 103,
															},
															width = "184",
															ZOrder = "1",
														},
														{
															controlID = "ScrollView_award_Panel_cur_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "498a7586_0d56_42b4_948e_a231ab8d45b8",
															anchorPoint = "False",
															anchorPointX = "0",
															anchorPointY = "0",
															backGroundScale9Enable = "False",
															bgColorOpacity = "50",
															bIsOpenClipping = "True",
															bounceEnable = "False",
															classname = "MEScrollView",
															colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
															direction = "2",
															dstBlendFunc = "771",
															height = "66",
															ignoreSize = "False",
															innerHeight = "66",
															innerWidth = "198",
															name = "ScrollView_award",
															showScrollbar = "False",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															touchAble = "True",
															UILayoutViewModel = 
															{
																PositionX = 4,
																PositionY = 4,
															},
															uipanelviewmodel = 
															{
																Layout="Absolute",
																nType = "0"
															},
															width = "198",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Panel_next_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "cfe5a7a0_058a_47f6_8475_30d5088b98fd",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "123",
													ignoreSize = "False",
													name = "Panel_next_reward",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 209,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "206",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_bg_Panel_next_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "471f0ae4_e4c0_4fd4_80fa_29abb86c788c",
															anchorPoint = "False",
															anchorPointX = "0",
															anchorPointY = "0",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "123",
															ignoreSize = "True",
															name = "Image_bg",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/tong/elite/002.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "206",
															ZOrder = "1",
														},
														{
															controlID = "Label_tip_Panel_next_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "1499cb6e_bd20_4f9d_9df7_cfe0db0dfff7",
															anchorPoint = "False",
															anchorPointX = "0",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF126280",
															fontName = "font/MFLiHei_Noncommercial.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_tip",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "Nächste Phase",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionX = 3,
																PositionY = 106,
															},
															width = "137",
															ZOrder = "1",
														},
														{
															controlID = "ScrollView_next_award_Panel_next_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "82765e59_9b92_40c6_88fe_dae5591742ac",
															anchorPoint = "False",
															anchorPointX = "0",
															anchorPointY = "0",
															backGroundScale9Enable = "False",
															bgColorOpacity = "50",
															bIsOpenClipping = "True",
															bounceEnable = "False",
															classname = "MEScrollView",
															colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
															direction = "2",
															dstBlendFunc = "771",
															height = "66",
															ignoreSize = "False",
															innerHeight = "66",
															innerWidth = "198",
															name = "ScrollView_next_award",
															showScrollbar = "False",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															touchAble = "True",
															UILayoutViewModel = 
															{
																PositionX = 5,
																PositionY = 5,
															},
															uipanelviewmodel = 
															{
																Layout="Absolute",
																nType = "0"
															},
															width = "198",
															ZOrder = "1",
														},
														{
															controlID = "Label_blood_tip_Panel_next_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "bcce4bc9_7a59_425d_b295_a57fe1487fd3",
															anchorPoint = "False",
															anchorPointX = "0",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF126280",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_blood_tip",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "HP reduces to 40",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionX = 3,
																PositionY = 82,
															},
															width = "128",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Panel_one_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "cb1535f0_50d6_4c29_9332_114d48a22356",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "123",
													ignoreSize = "False",
													name = "Panel_one_reward",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 208,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													visible = "False",
													width = "206",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_bg_Panel_one_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "160556e5_a4a4_4125_88b9_7ada1b3995e6",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0",
															backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "123",
															ignoreSize = "False",
															name = "Image_bg",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/tong/elite/002.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "400",
															ZOrder = "1",
														},
														{
															controlID = "Label_cur_tip_Panel_one_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "90f54a9f_519f_4e1c_bb9c_30fd1694b2cd",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF126280",
															fontName = "font/MFLiHei_Noncommercial.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "22",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "25",
															ignoreSize = "True",
															name = "Label_cur_tip",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "Aktuelle Belohnung",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = 103,
															},
															width = "231",
															ZOrder = "1",
														},
														{
															controlID = "ScrollView_award_Panel_one_reward_Panel_reward_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "2554e861_7cfc_41dc_857d_c5101325d804",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0",
															backGroundScale9Enable = "False",
															bgColorOpacity = "50",
															bIsOpenClipping = "True",
															bounceEnable = "False",
															classname = "MEScrollView",
															colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
															direction = "2",
															dstBlendFunc = "771",
															height = "66",
															ignoreSize = "False",
															innerHeight = "66",
															innerWidth = "198",
															name = "ScrollView_award",
															showScrollbar = "False",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															touchAble = "True",
															UILayoutViewModel = 
															{
																PositionY = 4,
															},
															uipanelviewmodel = 
															{
																Layout="Absolute",
																nType = "0"
															},
															width = "198",
															ZOrder = "1",
														},
													},
												},
											},
										},
										{
											controlID = "Panel_remain_change_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "3b0d19d3_6cf8_46c5_9674_4f475815444d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "False",
											name = "Panel_remain_change",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 3,
												PositionY = -127,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_leftcnt_Panel_remain_change_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "47d43423_6ea2_4e5c_8735_9be6ad58f4c8",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF126280",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_leftcnt",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Remaining Challenge Chances",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 144,
														PositionY = 1,
													},
													width = "263",
													ZOrder = "1",
												},
												{
													controlID = "Button_add_cnt_Panel_remain_change_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "d662aa57_a0d2_43a5_b416_0bf9a522e3e6",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "40",
													ignoreSize = "True",
													name = "Button_add_cnt",
													normal = "ui/tong/elite/003.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 174,
														PositionY = -1,
													},
													UItype = "Button",
													width = "40",
													ZOrder = "1",
												},
												{
													controlID = "Image_gray_Panel_remain_change_Image_info_view_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "a1360247_437a_44f7_92aa_61c33c8799a9",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_gray",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													texturePath = "ui/tong/elite/003.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 174,
														PositionY = -1,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Button_close_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "c13fb60b_89dc_42a2_965a_c15b0646d780",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "52",
									ignoreSize = "True",
									name = "Button_close",
									normal = "ui/tong/squad/012.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 734,
										PositionY = 238,
									},
									UItype = "Button",
									width = "52",
									ZOrder = "1",
								},
								{
									controlID = "Button_detail_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "9505eb29_7862_4d02_909f_5c6ee1c58536",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "101",
									ignoreSize = "True",
									name = "Button_detail",
									normal = "ui/tong/elite/010.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -243,
										PositionY = 42,
									},
									UItype = "Button",
									width = "107",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMonsterView_1_Button_detail_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "d311e3f5_c382_4ff6_a44f_d21ab7ca3583",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_tongMonsterView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Details",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -40,
											},
											width = "75",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_record_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "77745058_fd83_4d7a_a9b5_124c02931a5b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "101",
									ignoreSize = "True",
									name = "Button_record",
									normal = "ui/tong/elite/009.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -243,
										PositionY = -66,
									},
									UItype = "Button",
									width = "107",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMonsterView_1_Button_record_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "5c53faf7_21ac_4a85_bf2c_f06bfbffeaa7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_tongMonsterView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Record",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -40,
											},
											width = "77",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "e0cd4657_030f_4680_9b9d_e416623aadcd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "119",
									ignoreSize = "True",
									name = "Image_baseInfo",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/elite/006.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -110,
										PositionY = -215,
									},
									width = "356",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_hp_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "ca360a93_0424_4154_a1de_c6291ded1669",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "119",
											ignoreSize = "False",
											name = "Panel_hp",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "356",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_ttitle_Panel_hp_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "0e008b41_d7ac_47e5_9b0a_492f732a7d12",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFD0E9ED",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "Label_ttitle",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "HP",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -159,
														PositionY = 30,
													},
													width = "42",
													ZOrder = "1",
												},
												{
													controlID = "Image_hp_Panel_hp_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
													UUID = "64cf4d96_8e79_4528_b734_861e5770553d",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "14",
													ignoreSize = "True",
													name = "Image_hp",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/tong/elite/004.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -4,
														PositionY = 9,
													},
													width = "314",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "LoadingBar_hp_Image_hp_Panel_hp_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
															UUID = "2674fbd4_8b92_4006_bb21_fdcc4834dbe9",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MELoadingBar",
															direction = "0",
															dstBlendFunc = "771",
															height = "14",
															ignoreSize = "True",
															name = "LoadingBar_hp",
															percent = "0",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texture = "ui/tong/elite/005.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																LeftPositon = 838,
																TopPosition = 189,
																relativeToName = "Panel",
															},
															width = "314",
															ZOrder = "1",
															components = 
															{
																
																{
																	controlID = "Label_hp_LoadingBar_hp_Image_hp_Panel_hp_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
																	UUID = "d00c05aa_69e9_43eb_b101_6db69fb1d9a0",
																	anchorPoint = "False",
																	anchorPointX = "1",
																	anchorPointY = "0.5",
																	classname = "MELabel",
																	compPath = "luacomponents.common.MEIconLabel",
																	dstBlendFunc = "771",
																	FontColor = "#FFD0E9ED",
																	fontName = "font/fangzheng_zhunyuan.ttf",
																	fontShadow = 
																	{
																		IsShadow = false,
																		ShadowColor = "#FFFFFFFF",
																		ShadowAlpha = 255,
																		OffsetX = 0,
																		OffsetY = 0,
																	},
																	fontSize = "22",
																	fontStroke = 
																	{
																		IsStroke = false,
																		StrokeColor = "#FFE6E6E6",
																		StrokeSize = 1,
																	},
																	height = "25",
																	ignoreSize = "True",
																	name = "Label_hp",
																	nTextAlign = "1",
																	nTextHAlign = "1",
																	sizepercentx = "0",
																	sizepercenty = "0",
																	sizeType = "0",
																	srcBlendFunc = "770",
																	text = "42",
																	touchAble = "False",
																	touchScaleEnable = "False",
																	UILayoutViewModel = 
																	{
																		PositionX = 157,
																		PositionY = 24,
																	},
																	width = "26",
																	ZOrder = "1",
																},
															},
														},
													},
												},
											},
										},
										{
											controlID = "Label_lefttime_title_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "e9861036_1377_4e06_875c_fb0e70b99eb3",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF05383F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_lefttime_title",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Verbleibende Zeit",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -162,
												PositionY = -35,
											},
											width = "185",
											ZOrder = "1",
										},
										{
											controlID = "Label_lefttime_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "9f409c88_5969_4b17_b690_87c66b2ddaf6",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF05383F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_lefttime",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "42",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 35,
												PositionY = -35,
											},
											width = "24",
											ZOrder = "1",
										},
										{
											controlID = "Label_askHelp_effect_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "03120a8c_5542_44ff_bbd9_56af0cdd832c",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF05383F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_askHelp_effect",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "None",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 5,
												PositionY = -12,
											},
											width = "46",
											ZOrder = "1",
										},
										{
											controlID = "Label_askHelp_title_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "eb52842d_1550_48ac_b7c8_bde2e75f5070",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF05383F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_askHelp_title",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Support Bonus",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -162,
												PositionY = -13,
											},
											width = "159",
											ZOrder = "1",
										},
										{
											controlID = "Label_monster_state_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "5e2f946b_079c_4b2d_8f49_d98f7d95bf8e",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF05383F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_monster_state",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Killed",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 29,
												PositionY = -35,
											},
											width = "49",
											ZOrder = "1",
										},
										{
											controlID = "Label_state_title_Image_baseInfo_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "7fec10b9_2a86_46af_8bca_b665ef7bd8e5",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF05383F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_state_title",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Current Status",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -159,
												PositionY = -35,
											},
											width = "155",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_fight_ready_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "2de916a4_4d64_415f_a0f3_37cf524efa01",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_fight_ready",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 652,
										PositionY = -206,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMonsterView_1_Button_fight_ready_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "1fdb1f4c_ad3a_481f_820f_7ed899c4d9e4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_tongMonsterView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Prepare",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "76",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_ask_help_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "ad4fc356_aaed_426f_9687_6fe8b90099b9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_ask_help",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 517,
										PositionY = -205,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMonsterView_1_Button_ask_help_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "bebc572a_53d3_4264_b200_b8f2dfcf9f4c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_tongMonsterView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Ask for Support",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "114",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_retreat_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "4733779f_9338_4e92_83b5_06e841466c7b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_retreat",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 381,
										PositionY = -205,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tongMonsterView_1_Button_retreat_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "e15ed502_8651_4bb8_abad_a662c1aab2cc",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_tongMonsterView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Retreat",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "114",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_get_award_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "d5e519bc_0fa5_4444_9b90_1524ad865bff",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_get_award",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 517,
										PositionY = -206,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_btn_award_Button_get_award_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
											UUID = "9fa3f7bc_7bec_4613_a739_0226f660d23b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_btn_award",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Claim Reward",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "114",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_level_up_Image_left_bg_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "0dbbffac_2c59_4afb_9dbd_09d8912562b0",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_level_up",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/elite_levelup/VITmax_effect_elite_levelup",
										animationName = "action1",
										IsLoop = false,
										IsPlay = false,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -138,
										PositionY = 203,
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_buff_item_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
							UUID = "84dab1bd_0df2_42f0_9485_46c7c8e29cd2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "50",
							ignoreSize = "False",
							name = "Panel_buff_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -369,
								PositionY = -215,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "55",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg_Panel_buff_item_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "8663e15d_71b6_4650_8c02_18c383fee548",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "84",
									ignoreSize = "True",
									name = "Image_bg",
									scaleX = "0.6",
									scaleY = "0.6",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/elite/015.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "97",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_buff_item_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "0310f287_e93b_4517_9e85_caed2e22037e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_icon",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/affix/affix_1_jiansu.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
									},
									width = "110",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_buff_item_b_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
							UUID = "3ce58ed4_7f02_441f_96ff_5e098454cff5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "Panel_buff_item_b",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -369,
								PositionY = -215,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "97",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg_Panel_buff_item_b_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "4ff3712d_daa9_407c_a4f8_fe862b2696bc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "84",
									ignoreSize = "True",
									name = "Image_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/elite/015.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "97",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_buff_item_b_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
									UUID = "b071bf94_3091_495c_ac29_434a9e429bdf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_icon",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/affix/affix_1_jiansu.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
									},
									width = "110",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_dress_Panel_root_Panel-tongMonsterView_Layer1_tong_Game",
							UUID = "568fdfa2_4109_4383_99eb_a9386a831326",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "62",
							ignoreSize = "True",
							name = "Image_dress",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/elite/007.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -528,
								PositionY = 545,
							},
							width = "61",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/tong/elite/left.png",
			"ui/tong/elite/008.png",
			"ui/tong/squad/barbg.png",
			"ui/tong/squad/bar1.png",
			"ui/tong/elite/bg.png",
			"ui/tong/elite/002.png",
			"ui/tong/elite/003.png",
			"ui/tong/squad/012.png",
			"ui/tong/elite/010.png",
			"ui/tong/elite/009.png",
			"ui/tong/elite/006.png",
			"ui/tong/elite/004.png",
			"ui/tong/elite/005.png",
			"ui/tong/common/btn1.png",
			"ui/tong/elite/015.png",
			"icon/affix/affix_1_jiansu.png",
			"ui/tong/elite/007.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

