local t = 
{
	version = 2,
	components = 
	{
		
		{
			controlID = "Panel-tongReadyView_Layer1_tong_Game",
			UUID = "4afd06e9_8dc8_419f_ba33_3e8a66d7a362",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-tongReadyView_Layer1_tong_Game",
					UUID = "a082bb33_501c_4695_83d6_4213e7a75d96",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1386",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_content_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "1567fb23_f8c8_4ffa_9e5e_75d170293b51",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "442",
							ignoreSize = "True",
							name = "Image_content",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/squad/fight.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -7,
								LeftPositon = -325,
								TopPosition = 598,
								relativeToName = "Panel_root",
							},
							width = "751",
							ZOrder = "1",
						},
						{
							controlID = "Panel_costPos_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "2ae87d3c_15da_4402_ab5d_a83f0ee078f5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "56",
							ignoreSize = "False",
							name = "Panel_costPos",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 127,
								PositionY = -141,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "111",
							ZOrder = "1",
						},
						{
							controlID = "Button_close_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "5c77d07a_2acf_48b1_a228_4526fcc8ba69",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "52",
							ignoreSize = "True",
							name = "Button_close",
							normal = "ui/tong/squad/012.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 339,
								PositionY = 183,
							},
							UItype = "Button",
							width = "52",
							ZOrder = "1",
						},
						{
							controlID = "Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "b663f4c5_7202_45ca_baca_94f3bb0a518b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "429",
							ignoreSize = "False",
							name = "Panel_dating",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "1",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -9,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "740",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_datingDesc_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "9a01913b_09f8_493d_94de_e4c531133d1d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "127",
									ignoreSize = "True",
									name = "Image_datingDesc",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/squad/013-2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -121,
										PositionY = 92,
									},
									width = "404",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_datingDescTitle_Image_datingDesc_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "64db9938_eff7_45b7_831d_cdc26d1ebf56",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_datingDescTitle",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Abschlussbedingungen",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -158,
												PositionY = 38,
											},
											width = "242",
											ZOrder = "1",
										},
										{
											controlID = "Label_datingDesc_Image_datingDesc_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "6dc0a1e2_df60_4e41_98a9_783c08e62019",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_datingDesc",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Questbeschreibung",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -18,
											},
											width = "360",
											ZOrder = "1",
										},
										{
											controlID = "Image_flag_Image_datingDesc_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "49834f77_1b7e_4bed_a9f2_c90518ea16fc",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "23",
											ignoreSize = "True",
											name = "Image_flag",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/squad/009.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -180,
												PositionY = 41,
											},
											width = "24",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_datingTarget_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "47c15fcd_b416_41ab_bb5e_d86f97788acc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "127",
									ignoreSize = "True",
									name = "Image_datingTarget",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/squad/013-2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -121,
										PositionY = -37,
									},
									width = "404",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_datingTargetTitle_Image_datingTarget_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "75b3867c_41a4_4f7a_bd5b_64ed06a851ad",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_datingTargetTitle",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Abschlussbedingungen",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -158,
												PositionY = 36,
											},
											width = "242",
											ZOrder = "1",
										},
										{
											controlID = "Label_datingTarget_Image_datingTarget_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "2252a019_fa81_495a_bb56_8382083a20d3",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_datingTarget",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Questziel",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -18,
											},
											width = "360",
											ZOrder = "1",
										},
										{
											controlID = "Image_datingStar_Image_datingTarget_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "7485c62f_9c7b_4f39_a0c4_0bd24de2268f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "23",
											ignoreSize = "True",
											name = "Image_datingStar",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/squad/009.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -179,
												PositionY = 41,
											},
											width = "24",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_dating_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "e38de952_b7d8_4fc3_a45a_d7046a4fc164",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_dating",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 259,
										PositionY = -137,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_dating_Button_dating_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "ec3cc65e_2d6a_4e3a_b1d5_8a71ce0f248f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_dating",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Date starten",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "129",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_dating_reward_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "c50d9144_610b_4f53_b9ea_ee6399ea01dc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF0A636F",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "0",
									ignoreSize = "False",
									name = "Label_dating_reward",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "[1st Clearance Rewards]",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 200,
										PositionY = 132,
									},
									width = "225",
									ZOrder = "1",
								},
								{
									controlID = "Panel_reward_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "1b9aff22_cdda_4920_aac0_4a8bec4e7bf4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "271",
									ignoreSize = "False",
									name = "Panel_reward",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 254,
										PositionY = 20,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "200",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_reward_bg_Panel_reward_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "dd0d1320_984f_455c_939a_7aced4cc377a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "256",
											ignoreSize = "True",
											name = "Image_reward_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/squad/014-2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -48,
												PositionY = 5,
											},
											width = "235",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_reward_Panel_reward_Panel_dating_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "0dc17a78_0057_4553_8346_9bbfb7ae32b6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "True",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "1",
											dstBlendFunc = "771",
											height = "200",
											ignoreSize = "False",
											innerHeight = "200",
											innerWidth = "200",
											name = "ScrollView_reward",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -48,
												PositionY = -11,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "200",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "4976cc37_954f_4f61_b40c_dce6c86f9cbe",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "429",
							ignoreSize = "False",
							name = "Panel_fighting",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "1",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -9,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "740",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_cond_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "be105211_3a96_46b9_bafa_a53ec0128815",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "115",
									ignoreSize = "False",
									name = "Image_cond",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/squad/006.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 4,
										PositionY = 95,
									},
									width = "649",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_condTitle_Image_cond_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "738ee71b_92d6_45e0_8ad7_c76f5791e533",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_condTitle",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Clear Conditions",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -285,
												PositionY = 35,
											},
											width = "176",
											ZOrder = "1",
										},
										{
											controlID = "Label_cond_Image_cond_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "c0d638c4_8567_4f7d_85c9_df2323c2df35",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF458F9B",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_cond",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Defeat all enemies",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -280,
												PositionY = 2,
											},
											width = "161",
											ZOrder = "1",
										},
										{
											controlID = "Image_fight_icon_Image_cond_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "2a11e49f_144c_4e94_86e6_9c7641a72cac",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "23",
											ignoreSize = "True",
											name = "Image_fight_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/squad/009.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -306,
												PositionY = 39,
											},
											width = "24",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "ca1e952c_2595_4a53_b6d5_f83969cf6f93",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "132",
									ignoreSize = "True",
									name = "Image_target",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/squad/006.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 4,
										PositionY = -32,
									},
									width = "649",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_targetTitle_Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "ff72d687_a9d3_4629_90d9_6749ba6610fe",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_targetTitle",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Elite Reaction Points",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 83,
												PositionY = 45,
											},
											width = "226",
											ZOrder = "1",
										},
										{
											controlID = "Label_nextPoint_Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "522e26d3_6760_41d0_90a0_0d98f92e652e",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_nextPoint",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "70",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 168,
												PositionY = -4,
											},
											width = "28",
											ZOrder = "1",
										},
										{
											controlID = "Label_curPoint_Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "af5f1c43_e401_4dc9_9352_224377998ef5",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_curPoint",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "60",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 110,
												PositionY = -5,
											},
											width = "28",
											ZOrder = "1",
										},
										{
											controlID = "Image_arow_Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "f40f2fb8_53c0_4810_a7bd_99e1959c3d1a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "19",
											ignoreSize = "True",
											name = "Image_arow",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/squad/010.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 141,
												PositionY = -4,
											},
											width = "26",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_fight_award_Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "16c4f9e1_fbd4_4935_96bd_ac43bd7e3a57",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "2",
											dstBlendFunc = "771",
											height = "88",
											ignoreSize = "False",
											innerHeight = "88",
											innerWidth = "280",
											name = "ScrollView_fight_award",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -307,
												PositionY = -57,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "280",
											ZOrder = "1",
										},
										{
											controlID = "Label_over_point_Image_target_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "edcc69df_ba23_44df_a9f2_38d7b2af4135",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF0A636F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_over_point",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "(Maxed)",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 200,
												PositionY = -4,
											},
											width = "86",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_fighting_reward_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "1b2e459c_0871_4261_bd02_9a6147a65f0e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF0A636F",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_fighting_reward",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Possible Drops",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -225,
										PositionY = 12,
									},
									width = "157",
									ZOrder = "1",
								},
								{
									controlID = "Button_ready_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "f1530aa5_611b_4917_a7df_859bd279e13a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "89",
									ignoreSize = "True",
									name = "Button_ready",
									normal = "ui/tong/common/btn1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 263,
										PositionY = -132,
									},
									UItype = "Button",
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_ready_Button_ready_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "ed7d93b6_1efd_4897_bd0e_56c8e654b9e5",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_ready",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Prepare",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "82",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_select_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "5e3f6349_4d8c_4a0e_97d7_3f68c8cc445b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_select",
									normal = "ui/fuben/001.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 156,
										PositionY = -130,
									},
									UItype = "Button",
									width = "56",
									ZOrder = "1",
								},
								{
									controlID = "Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "b10a3d88_520b_45dd_8aa0_49b6e60d46df",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_difficulty",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -324,
										PositionY = -159,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "400",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_diff_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "9d44f659_0ccc_4df4_8754_950b4f6e56cf",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "False",
											name = "Panel_diff",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 134,
												PositionY = 55,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											visible = "False",
											width = "155",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Button_diff_1_Panel_diff_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
													UUID = "df7fccfe_1c01_492f_b07e_8906394bc082",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "51",
													ignoreSize = "False",
													name = "Button_diff_1",
													normal = "ui/tong/squad/004.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionY = 76,
													},
													UItype = "Button",
													width = "155",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Label_diff_Button_diff_1_Panel_diff_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
															UUID = "6aa9aca8_01c2_4d19_926b_47a3bbaa1faa",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF0A636F",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "24",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "27",
															ignoreSize = "True",
															name = "Label_diff",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "Schwieriger Modus",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "186",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Button_diff_2_Panel_diff_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
													UUID = "ba1ccdca_79ba_493f_bab4_f91b04e094fa",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "51",
													ignoreSize = "False",
													name = "Button_diff_2",
													normal = "ui/tong/squad/004.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionY = 25,
													},
													UItype = "Button",
													width = "155",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Label_diff_Button_diff_2_Panel_diff_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
															UUID = "75550878_4472_45e1_8be4_eba2109d0050",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF0A636F",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "24",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "27",
															ignoreSize = "True",
															name = "Label_diff",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "Schwieriger Modus",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "186",
															ZOrder = "1",
														},
													},
												},
											},
										},
										{
											controlID = "Button_diff_select_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "2a8962bf_2f26_4339_8b44_c975404e3237",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "51",
											ignoreSize = "False",
											name = "Button_diff_select",
											normal = "ui/tong/squad/004.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 187,
												PositionY = 30,
											},
											UItype = "Button",
											width = "178",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_diff_select_Button_diff_select_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
													UUID = "6a35bca0_69e3_4411_ad18_d7764511ec9e",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF0A636F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "Label_diff_select",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Normal",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -12,
													},
													width = "76",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Button_diff_select_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
													UUID = "41512b9b_fd93_4871_9471_5e8b8b18f34e",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "21",
													ignoreSize = "True",
													name = "Image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/tong/squad/008.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 69,
														PositionY = -1,
													},
													width = "25",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Image_tongReadyView_1_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
											UUID = "5d79c2b2_a3ef_40f0_b1fb_87fbf39e4ec4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "51",
											ignoreSize = "False",
											name = "Image_tongReadyView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/squad/004.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 43,
												PositionY = 30,
											},
											width = "102",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_tongReadyView_1_Image_tongReadyView_1_Panel_difficulty_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
													UUID = "d2c035fc_a872_4ef1_8ce9_00dadc9280d3",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF0A636F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "Label_tongReadyView_1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Battle Difficulty",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "94",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Label_time_Panel_fighting_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "dbaac59e_96da_4311_a66c_f03d435ff2c0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF458F9B",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_time",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Remaining Time",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -276,
										PositionY = 61,
									},
									width = "146",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Label_name_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "90201607_ce76_400a_b0ea_6ecf56ddd8d4",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF0A636F",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "28",
							ignoreSize = "True",
							name = "Label_name",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "1-1",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = 162,
							},
							width = "37",
							ZOrder = "1",
						},
						{
							controlID = "Button_cost_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
							UUID = "bfd92a85_8118_46b4_a597_877883c0153f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "56",
							ignoreSize = "False",
							name = "Button_cost",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 70,
								PositionY = -141,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "111",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_tongReadyView_1_Button_cost_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "d3686bbb_9499_473e_b1d8_97a50303c553",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "56",
									ignoreSize = "True",
									name = "Image_tongReadyView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/squad/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "111",
									ZOrder = "1",
								},
								{
									controlID = "Label_costNum_Button_cost_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "c92b0dfc_96f3_42e3_9e64_385fcc1d85fc",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "33",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FFA8AAAA",
										StrokeSize = 1,
									},
									height = "40",
									ignoreSize = "True",
									name = "Label_costNum",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "10",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -6,
										PositionY = -4,
									},
									width = "39",
									ZOrder = "1",
								},
								{
									controlID = "Image_costIcon_Button_cost_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "7804c390_02a3_4921_b4f7_4c6ca9ab7db1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_costIcon",
									scaleX = "0.25",
									scaleY = "0.25",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/item/goods/510401.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 24,
										PositionY = 13,
									},
									width = "100",
									ZOrder = "1",
								},
								{
									controlID = "Label_cost_Button_cost_Panel_root_Panel-tongReadyView_Layer1_tong_Game",
									UUID = "b319a375_beab_497f_bbfb_af326f2dec3f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FFA8AAAA",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_cost",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Cost",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 21,
										PositionY = -14,
									},
									width = "41",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-tongReadyView_Layer1_tong_Game",
					UUID = "b223edd1_1af8_4055_995a_30f918e378c6",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFFFF5EE;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 26,
						PositionY = -729,
						LeftPositon = 26,
						TopPosition = 729,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/tong/squad/fight.png",
			"ui/tong/squad/012.png",
			"ui/tong/squad/013-2.png",
			"ui/tong/squad/009.png",
			"ui/tong/common/btn1.png",
			"ui/tong/squad/014-2.png",
			"ui/tong/squad/006.png",
			"ui/tong/squad/010.png",
			"ui/fuben/001.png",
			"ui/tong/squad/004.png",
			"ui/tong/squad/008.png",
			"ui/tong/squad/005.png",
			"icon/item/goods/510401.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

