return {
    [1] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/011.png",
        id = 1,
        icon = "icon/chatBubble/chatUseRes/010.png",
        portraitid = 20000,
    },
    [2] = {
        overturnType = 1,
        othericon = "",
        id = 2,
        icon = "icon/chatBubble/chatUseRes/005.png",
        portraitid = 20001,
    },
    [3] = {
        overturnType = 1,
        othericon = "",
        id = 3,
        icon = "icon/chatBubble/chatUseRes/003.png",
        portraitid = 20002,
    },
    [6] = {
        overturnType = 1,
        othericon = "",
        id = 6,
        icon = "icon/chatBubble/chatUseRes/006.png",
        portraitid = 20005,
    },
    [7] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/004.png",
        id = 7,
        icon = "icon/chatBubble/chatUseRes/001.png",
        portraitid = 20006,
    },
    [8] = {
        overturnType = 1,
        othericon = "",
        id = 8,
        icon = "icon/chatBubble/chatUseRes/002.png",
        portraitid = 20007,
    },
    [9] = {
        overturnType = 1,
        othericon = "",
        id = 9,
        icon = "icon/chatBubble/chatUseRes/014.png",
        portraitid = 20008,
    },
    [10] = {
        overturnType = 1,
        othericon = "",
        id = 10,
        icon = "icon/chatBubble/chatUseRes/015.png",
        portraitid = 20009,
    },
    [11] = {
        overturnType = 1,
        othericon = "",
        id = 11,
        icon = "icon/chatBubble/chatUseRes/101.png",
        portraitid = 20010,
    },
    [12] = {
        overturnType = 1,
        othericon = "",
        id = 12,
        icon = "icon/chatBubble/chatUseRes/018.png",
        portraitid = 20011,
    },
    [13] = {
        overturnType = 1,
        othericon = "",
        id = 13,
        icon = "icon/chatBubble/chatUseRes/018.png",
        portraitid = 20012,
    },
    [14] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/020.png",
        id = 14,
        icon = "icon/chatBubble/chatUseRes/019.png",
        portraitid = 20013,
    },
    [15] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/022.png",
        id = 15,
        icon = "icon/chatBubble/chatUseRes/021.png",
        portraitid = 20014,
    },
    [16] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/024.png",
        id = 16,
        icon = "icon/chatBubble/chatUseRes/023.png",
        portraitid = 20015,
    },
    [18] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/027.png",
        id = 18,
        icon = "icon/chatBubble/chatUseRes/026.png",
        portraitid = 20017,
    },
    [51] = {
        overturnType = 1,
        othericon = "",
        id = 51,
        icon = "icon/chatBubble/chatUseRes/082.png",
        portraitid = 60018,
    },
    [50] = {
        overturnType = 0,
        othericon = "icon/chatBubble/chatUseRes/081.png",
        id = 50,
        icon = "icon/chatBubble/chatUseRes/080.png",
        portraitid = 60015,
    },
}