return {
    [1] = {
        map = 1,
        posId = 1,
        showByPreDun = 0,
        isReplaceable = false,
        id = 1,
        defaultDungeon = 101,
        stage = 1,
        tag = "story.1",
    },
    [2] = {
        map = 1,
        posId = 2,
        showByPreDun = 0,
        isReplaceable = false,
        id = 2,
        defaultDungeon = 102,
        stage = 1,
        tag = "story.2",
    },
    [3] = {
        map = 1,
        posId = 3,
        showByPreDun = 0,
        isReplaceable = false,
        id = 3,
        defaultDungeon = 103,
        stage = 1,
        tag = "story.3",
    },
    [4] = {
        map = 1,
        posId = 4,
        showByPreDun = 0,
        isReplaceable = false,
        id = 4,
        defaultDungeon = 104,
        stage = 1,
        tag = "story.4",
    },
    [5] = {
        map = 1,
        posId = 5,
        showByPreDun = 0,
        isReplaceable = false,
        id = 5,
        defaultDungeon = 105,
        stage = 1,
        tag = "story.5",
    },
    [6] = {
        map = 1,
        posId = 6,
        showByPreDun = 0,
        isReplaceable = false,
        id = 6,
        defaultDungeon = 106,
        stage = 1,
        tag = "story.6",
    },
    [7] = {
        map = 1,
        posId = 7,
        showByPreDun = 0,
        isReplaceable = false,
        id = 7,
        defaultDungeon = 107,
        stage = 1,
        tag = "story.7",
    },
    [8] = {
        map = 1,
        posId = 8,
        showByPreDun = 0,
        isReplaceable = false,
        id = 8,
        defaultDungeon = 108,
        stage = 1,
        tag = "story.8",
    },
    [9] = {
        map = 1,
        posId = 9,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 9,
        defaultDungeon = 109,
        stage = 2,
        tag = "story.9",
    },
    [10] = {
        map = 1,
        posId = 10,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 10,
        defaultDungeon = 110,
        stage = 2,
        tag = "story.10",
    },
    [11] = {
        map = 1,
        posId = 11,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 11,
        defaultDungeon = 111,
        stage = 2,
        tag = "story.11",
    },
    [12] = {
        map = 1,
        posId = 12,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 12,
        defaultDungeon = 112,
        stage = 2,
        tag = "story.12",
    },
    [13] = {
        map = 1,
        posId = 13,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 13,
        defaultDungeon = 113,
        stage = 2,
        tag = "story.13",
    },
    [14] = {
        map = 1,
        posId = 14,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 14,
        defaultDungeon = 114,
        stage = 2,
        tag = "story.14",
    },
    [15] = {
        map = 1,
        posId = 15,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 15,
        defaultDungeon = 115,
        stage = 2,
        tag = "story.15",
    },
    [16] = {
        map = 1,
        posId = 16,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 16,
        defaultDungeon = 116,
        stage = 2,
        tag = "story.16",
    },
    [17] = {
        map = 1,
        posId = 17,
        showByPreDun = 281208,
        isReplaceable = false,
        id = 17,
        defaultDungeon = 117,
        stage = 3,
        tag = "story.17",
    },
    [18] = {
        map = 2,
        posId = 1,
        showByPreDun = 0,
        isReplaceable = true,
        id = 18,
        defaultDungeon = 301,
        stage = 1,
        tag = "ep.1",
    },
    [19] = {
        map = 2,
        posId = 2,
        showByPreDun = 0,
        isReplaceable = true,
        id = 19,
        defaultDungeon = 302,
        stage = 1,
        tag = "ep.2",
    },
    [20] = {
        map = 2,
        posId = 3,
        showByPreDun = 0,
        isReplaceable = true,
        id = 20,
        defaultDungeon = 303,
        stage = 1,
        tag = "ep.3",
    },
    [21] = {
        map = 2,
        posId = 4,
        showByPreDun = 0,
        isReplaceable = true,
        id = 21,
        defaultDungeon = 304,
        stage = 1,
        tag = "ep.4",
    },
    [22] = {
        map = 2,
        posId = 5,
        showByPreDun = 0,
        isReplaceable = true,
        id = 22,
        defaultDungeon = 305,
        stage = 1,
        tag = "ep.5",
    },
    [23] = {
        map = 2,
        posId = 6,
        showByPreDun = 0,
        isReplaceable = true,
        id = 23,
        defaultDungeon = 306,
        stage = 1,
        tag = "ep.6",
    },
    [24] = {
        map = 2,
        posId = 7,
        showByPreDun = 0,
        isReplaceable = true,
        id = 24,
        defaultDungeon = 307,
        stage = 1,
        tag = "ep.7",
    },
    [25] = {
        map = 2,
        posId = 8,
        showByPreDun = 0,
        isReplaceable = true,
        id = 25,
        defaultDungeon = 308,
        stage = 1,
        tag = "ep.8",
    },
    [26] = {
        map = 2,
        posId = 9,
        showByPreDun = 0,
        isReplaceable = true,
        id = 26,
        defaultDungeon = 309,
        stage = 2,
        tag = "ep.9",
    },
    [27] = {
        map = 2,
        posId = 10,
        showByPreDun = 0,
        isReplaceable = true,
        id = 27,
        defaultDungeon = 310,
        stage = 2,
        tag = "ep.10",
    },
    [28] = {
        map = 2,
        posId = 11,
        showByPreDun = 0,
        isReplaceable = true,
        id = 28,
        defaultDungeon = 311,
        stage = 2,
        tag = "ep.11",
    },
    [29] = {
        map = 2,
        posId = 12,
        showByPreDun = 0,
        isReplaceable = true,
        id = 29,
        defaultDungeon = 312,
        stage = 2,
        tag = "ep.12",
    },
    [30] = {
        map = 2,
        posId = 13,
        showByPreDun = 0,
        isReplaceable = true,
        id = 30,
        defaultDungeon = 313,
        stage = 2,
        tag = "ep.13",
    },
    [31] = {
        map = 2,
        posId = 14,
        showByPreDun = 0,
        isReplaceable = true,
        id = 31,
        defaultDungeon = 314,
        stage = 2,
        tag = "ep.14",
    },
    [32] = {
        map = 2,
        posId = 15,
        showByPreDun = 0,
        isReplaceable = true,
        id = 32,
        defaultDungeon = 315,
        stage = 2,
        tag = "ep.15",
    },
    [33] = {
        map = 2,
        posId = 16,
        showByPreDun = 0,
        isReplaceable = true,
        id = 33,
        defaultDungeon = 316,
        stage = 2,
        tag = "ep.16",
    },
}