local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-tongActivityMainView_Layer1_tong_Game",
			UUID = "8dc61e11_8093_4dd0_8437_0468b87648d3",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
					UUID = "f70aae13_a684_4a91_b777_af732474ce32",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "a29105b7_5725_498e_810a_83912f4b78e6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/tong/activity/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Button_close_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "a107e0e0_5216_4366_bd10_f81dd2fcaae1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "60",
							ignoreSize = "True",
							name = "Button_close",
							normal = "ui/common/pop_ui/pop_btn_02.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 295,
								PositionY = 199,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
						},
						{
							controlID = "Button_store_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "8fe65ee5_882c_483d_8caf_42dfc667dfa6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "106",
							ignoreSize = "True",
							name = "Button_store",
							normal = "ui/tong/activity/011.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 128,
								PositionY = 131,
								relativeToName = "Panel",
							},
							UItype = "Button",
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_store_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "275bf344_99ba_40be_8d48_ed3a7c7e60e6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "False",
									name = "Image_title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -38,
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_store_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "02bc4f48_75e4_45bb_adfc_14522b9e4382",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Event Store",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 8,
												PositionY = -2,
											},
											width = "124",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_store_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "25e8b748_9209_4d2e_8d7f_86b66f6e155a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/005.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -61,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_store_Button_store_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "4a6b7b87_23a2_4540_a047_ebc233bf3c53",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_store",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/store/VITmax_effect_main_store",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										relativeToName = "Panel",
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "f675af42_d4ea_4941_9368_3872b706245b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "199",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_map",
							normal = "ui/tong/activity/015.png",
							pressed = "ui/tong/activity/015.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 51,
								PositionY = -48,
							},
							UItype = "Button",
							width = "335",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "26318d79_5b70_4db5_8656_6c017a0d6f1a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "False",
									name = "Image_title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 2,
										PositionY = -36,
									},
									width = "153",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "4abc2a29_55fd_41e4_b178_d909f19fdb92",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Battle Map",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 11,
												PositionY = -2,
											},
											width = "116",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "ea7ed60a_fc5f_4de0_b78b_fc04c0224ea2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/007.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -60,
												PositionY = 1,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_map_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "ab3b331d_e02f_472b_8455_3042a62aa88a",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_map",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/map/VITmax_effect_main_map",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 23,
									},
									ZOrder = "1",
								},
								{
									controlID = "Spine_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "3b9825c4_c328_4030_ab81_c2a1d6cdec19",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/boss/VITmax_effect_main_boss",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -7,
										PositionY = 11,
									},
									ZOrder = "1",
								},
								{
									controlID = "Spine_supply_flag_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "d3745830_0875_4386_9382_1ca7e3e7ff4b",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_supply_flag",
									scaleX = "0.35",
									scaleY = "0.35",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/VITmax_effect_level_supply",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -45,
										PositionY = 20,
									},
									ZOrder = "1",
								},
								{
									controlID = "Spine_elite_flag_Button_map_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "8786062e_46b2_4349_b3f0_c0fd65969e33",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_elite_flag",
									scaleX = "0.3",
									scaleY = "0.3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/VITmax_effect_level_elite",
										animationName = "progress",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 35,
										PositionY = 25,
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_boss_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "013b41bf_11ff_4a9c_b45c_922e597ba684",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "125",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_boss",
							normal = "ui/tong/activity/tree.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 31,
								PositionY = 44,
							},
							UItype = "Button",
							width = "122",
							ZOrder = "1",
						},
						{
							controlID = "Button_rank_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "3a45a440_b9b5_4620_8324_70ead25b8b54",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "191",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_rank",
							normal = "ui/tong/activity/014.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -169,
								PositionY = 198,
							},
							UItype = "Button",
							width = "274",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_rank_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "cda0059b_416b_47f9_946f_d41e8f5ee391",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "False",
									name = "Image_title",
									rotation = "-12",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 20,
										PositionY = -78,
									},
									width = "204",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_rank_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "745a7275_5da1_45cd_851e_9797cfd480b2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "View Rankings",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 13,
												PositionY = -1,
											},
											width = "159",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_rank_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "0f276667_232d_4259_8682_f1ef67b7702d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											rotation = "10",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/004.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -83,
												PositionY = 2,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_rank_Button_rank_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "7b487f01_af8b_4216_b133_8ff0ee7f9498",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_rank",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/rank/VITmax_effect_main_rank",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_other_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "58940d25_6f08_4e8d_9521_6d3ed88694f4",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "142",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_other",
							normal = "ui/tong/activity/017.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -356,
								PositionY = 21,
							},
							UItype = "Button",
							width = "126",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_other_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "b3759ba9_9f3e_4e22_9ddc_9999142dc767",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "False",
									name = "Image_title",
									rotation = "-15",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 26,
										PositionY = -69,
									},
									width = "165",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_other_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "5afc6eb6_8f40_4d52_a6f3_a7a9c6ecedd2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Other events",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 9,
												PositionY = -1,
											},
											width = "135",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_other_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "8ea69f44_1fe0_429d_a34a_f335e7185967",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											rotation = "10",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/003.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -67,
												PositionY = 2,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_other_Button_other_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "f261db5d_9995_47ce_9f82_bf2198204092",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_other",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/events/VITmax_effect_main_events",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_guide_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "e2c23b26_ee21_46d9_b0a7_1010bdf56254",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "94",
							ignoreSize = "True",
							name = "Button_guide",
							normal = "ui/tong/activity/009.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 119,
								PositionY = -145,
							},
							UItype = "Button",
							width = "65",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_guide_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "bc462c58_8f0c_43d5_a874_dc44c515d0b4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "False",
									name = "Image_title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -9,
										PositionY = -55,
									},
									width = "163",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_guide_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "14bce064_8e90_4d53_9729_244a0db83107",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Event-Intro",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 7,
												PositionY = -1,
											},
											width = "123",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_guide_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "d2b9cb6d_b450_41c3_a8bc_3869559ce629",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -65,
												PositionY = 1,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_guide_Button_guide_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "1eb64b85_4fed_4dc5_a6c4_f94eaef9a6d1",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_guide",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/help/VITmax_effect_main_help",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 3,
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_task_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "5fb1f268_5c12_4c9b_b5ac_9ef36a39d2a6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "79",
							ignoreSize = "True",
							name = "Button_task",
							normal = "ui/tong/activity/012.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -154,
							},
							UItype = "Button",
							width = "107",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_task_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "abae7d7e_afcf_4b8b_b915_dab9438efd3e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "True",
									name = "Image_title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -14,
										PositionY = -46,
									},
									width = "132",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_task_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "602d9a07_3471_4eac_ac56_2747b53fc850",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Quests",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 13,
												PositionY = -2,
											},
											width = "74",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_task_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "475e32cd_b5b4_4b03_9105_60a59674ec5f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -44,
												PositionY = 1,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_task_Button_task_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "e34b03e1_a05b_4747_9622_60c28e3156f4",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_task",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/task/VITmax_effect_main_task",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 1,
										PositionY = -5,
									},
									ZOrder = "1",
								},
								{
									controlID = "Image_redtip_Button_task_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "abad1b18_509e_4eee_a9dc_e24fce77ac20",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "True",
									name = "Image_redtip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/news_small.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 35,
										PositionY = 12,
									},
									width = "30",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_skill_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "10fbb220_6eda_4224_adeb_6e58ecc722b1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "88",
							ignoreSize = "True",
							name = "Button_skill",
							normal = "ui/tong/activity/010.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 276,
								PositionY = -93,
							},
							UItype = "Button",
							width = "103",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_Button_skill_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "f76de7ea_0ff2_44dc_a228_ef9812cc9e02",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "28",
									ignoreSize = "False",
									name = "Image_title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/tong/activity/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -2,
										PositionY = -49,
									},
									width = "152",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_text_Image_title_Button_skill_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "feaa2568_adba_449c_8991_f214f90454df",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF8D521E",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_text",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Skill Book",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 10,
											},
											width = "112",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Image_title_Button_skill_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
											UUID = "a0af0a6c_f4e0_4086_98b6_17e6d9c7f3d7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/tong/activity/006.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -60,
												PositionY = 1,
											},
											width = "38",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Spine_skill_Button_skill_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
									UUID = "1b5727bb_9623_432d_afde_dffc642653f8",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_skill",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/eff_vitmax/ui_main/skill/VITmax_effect_main_skill",
										animationName = "idle",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_tongActivityMainView_2_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "136e825d_3816_4366_8335_de16d18d2f8c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "34",
							ignoreSize = "True",
							name = "Image_tongActivityMainView_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/tong/activity/016.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 64,
								PositionY = -142,
							},
							width = "30",
							ZOrder = "1",
						},
						{
							controlID = "Spine_dress_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "7fbe9443_9aa0_4790_a172_eadcedf5f56d",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_dress",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/eff_vitmax/ui_main/mainScene/VITmax_effect_mainScene",
								animationName = "animation",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 31,
								PositionY = 3,
							},
							ZOrder = "1",
						},
						{
							controlID = "Panel_mask_Panel_root_Panel-tongActivityMainView_Layer1_tong_Game",
							UUID = "55cd048a_5e41_4147_9553_ddee7cbfe567",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "255",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "400",
							ignoreSize = "False",
							name = "Panel_mask",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "400",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/tong/activity/bg.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/tong/activity/011.png",
			"ui/tong/activity/008.png",
			"ui/tong/activity/005.png",
			"ui/tong/activity/015.png",
			"ui/tong/activity/007.png",
			"ui/tong/activity/tree.png",
			"ui/tong/activity/014.png",
			"ui/tong/activity/004.png",
			"ui/tong/activity/017.png",
			"ui/tong/activity/003.png",
			"ui/tong/activity/009.png",
			"ui/tong/activity/001.png",
			"ui/tong/activity/012.png",
			"ui/tong/activity/002.png",
			"ui/common/news_small.png",
			"ui/tong/activity/010.png",
			"ui/tong/activity/006.png",
			"ui/tong/activity/016.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

