local t = {
		{
			name="tongMainView",
			ui ="tongMainView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongMap",
			ui ="tongMap.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongBossView",
			ui ="tongBossView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongMonsterView",
			ui ="tongMonsterView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongRetreatConfirmView",
			ui ="tongRetreatConfirmView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongBuffListView",
			ui ="tongBuffListView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongAskHelpView",
			ui ="tongAskHelpView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongHelpListView",
			ui ="tongHelpListView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongBossRewardView",
			ui ="tongBossRewardView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongRankView",
			ui ="tongRankView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongStudyMainView",
			ui ="tongStudyMainView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongEquipTipView",
			ui ="tongEquipTipView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongAttrDetailView",
			ui ="tongAttrDetailView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongReadyView",
			ui ="tongReadyView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongBossInfoView",
			ui ="tongBossInfoView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongFightRecordView",
			ui ="tongFightRecordView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongStoreView",
			ui ="tongStoreView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongTaskView",
			ui ="tongTaskView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongActivityMainView",
			ui ="tongActivityMainView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="tongAddNumConfirmView",
			ui ="tongAddNumConfirmView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		{
			name="buyResourceView",
			ui ="buyResourceView.lua",
			x=0,
			y=0,
			speed=0,
			layer="tong",
			canLoad=true,
			logic="",
		},
		
}
return t
